### ISSUE TITLE
Start Wrapsix Problem on Beaglebone Black Board

### ISSUE THREAD

**Issue by karlrenner214** [cetic/6lbr#101]
I am following the procedure at http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples to run 6lbr and wrapsix on a Beaglebone Black board.  After wrapsix is starting it seems to hang with no prompt returned.  Is this correct behavior?

debian@beaglebone:~$ sudo wrapsix &
[5] 10331
debian@beaglebone:~$ [Info] WrapSix 0.2.0 is starting

**Comment by laurentderu** [comment]
You should have some log information displaying the interface and ip addresses used (at least with the latest version of wrapsix)

**Comment by Zjion** [comment]
I believe it is correct behaviour. I am also running the set-up in the wiki. The steps are as follows in the guide:
screen
press any key
sudo wrapsix &
ctrl-A D to get out of screen

**Comment by laurentderu** [comment]
Thanks for the confirmation
