### ISSUE TITLE
Destination address changes at 6lbr

### ISSUE THREAD

**Issue by serdarkose** [cetic/6lbr#106]
Hi,

I have the similar set up as 6lbr-example has: 
Computer (bbbb::101) <--eth cable--> (bbbb::100)RPI + CC2531 (aaaa::x) <---wireless --> CC2650EM (aaaa:YYYY) 

When I ping or send a udp packet from my pc, the wireshark on my laptop shows correct destination address (aaaa::YYYY). However, the wireshark that sniffs the 6LoWPAN environment (through sensniff) shows the destination address as ::YYYY, aaaa part turns to 0000. Somehow it makes to the CC2650EM and I see L2 ACKs, but I guess it can't get the UDP packet to layer 3 as the destination address is wrong.

I added more information and description on https://e2e.ti.com/support/wireless_connectivity/f/158/t/456722

Today, I installed 6lbr on BeagleBoard-XM, I have the same problem on that one as well. 

- Is it normal that aaaa part address turns to 0000? If it is the case, how can I receive the UDP to higher layer?
-If there is a problem, how can I fix it?

**Comment by laurentderu** [comment]
It's not a problem, as 6LoWPAN compress IP headers and Wireshark is not aware of the preconfigured information, you have to manually configure Wireshark to properly decompress the 6LoWPAN frames. You have to do in Preferences -> 6LoWPAN and add your prefix "aaaa::" in Context 0.
