### ISSUE TITLE
Connecting a node from the edge router

### ISSUE THREAD

**Issue by chuijh** [cetic/6lbr#107]
I am sorry if it may sound similar to issue #85, as I am trying to connect to a node from the edge router without success. Can you give me advices on what I may have done wrong? Thanks!

Here is the conf file:

MODE=ROUTER
#MODE=SMART-BRIDGE
#MODE=RPL-RELAY
#MODE=FULL-TRANSPARENT-BRIDGE
#MODE=NDP-ROUTER
#MODE=6LR
#MODE=RPL-ROOT

RAW_ETH=1
BRIDGE=0
DEV_BRIDGE=br0
DEV_TAP=tap0
DEV_ETH=eth0
RAW_ETH_FCS=0

DEV_RADIO=/dev/ttyACM0
BAUDRATE=115200

#Enable this line if radio device is not detected
#SCAN_DEVICE=/usr/lib/6lbr/bb-scan-usb.sh

LOG_LEVEL=4 #INFO and above only

and here are the commands  I ran

debian@beaglebone:~$ sudo route -A inet6 add  aaaa::/64 eth0

debian@beaglebone:~$ sudo route -A inet6                                        
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
::1/128                        ::                         U    256 0     0 lo
aaaa::/64                      ::                         U    1   0     0 eth0
fe80::/64                      ::                         U    256 0     0 eth0
::/0                           ::                         !n   -1  1  3224 lo
::1/128                        ::                         Un   0   1     6 lo
fe80::6eec:ebff:feab:2ce5/128  ::                         Un   0   1   420 lo
ff00::/8                       ::                         U    256 0     0 eth0
::/0                           ::                         !n   -1  1  3224 lo

debian@beaglebone:~$ ping6 aaaa::212:4b00:78f:f407
PING aaaa::212:4b00:78f:f407(aaaa::212:4b00:78f:f407) 56 data bytes
From fe80::6eec:ebff:feab:2ce5 icmp_seq=1 Destination unreachable: Address unreachable
From fe80::6eec:ebff:feab:2ce5 icmp_seq=2 Destination unreachable: Address unreachable

**Comment by laurentderu** [comment]
Hello,

Your BR is working in Raw Ethernet configuration, in this configuration you can not have access to the BR from the beaglebone, you have to use Bridge configuration, see https://github.com/cetic/6lbr/wiki/6LBR-Interface-Configuration
