### ISSUE TITLE
date discrepancy in 6lbr log file

### ISSUE THREAD

**Issue by xianlin** [cetic/6lbr#108]
Anyone can advise how to troubleshoot the **date discrepancy** issue as below?

the 6lbr log `/var/log/6lbr.log` shows date **one month older** than the actual date as in command `date` output. (i.e. 22 Sep v.s. 22 Oct in the below case)

![6lbr_log_date_wrong](https://cloud.githubusercontent.com/assets/1726373/10657558/f57acf46-78bf-11e5-8f6f-2009b8aa58ac.png)

**Comment by laurentderu** [comment]
Hi,

This is a known issue (reported on the ML) and fixed in the develop branch. I'll close this when the snapshot is released.

**Comment by laurentderu** [comment]
Integrated and validated in the upcoming 1.4.0 release
