### ISSUE TITLE
Questions on SLIP Radio

### ISSUE THREAD

**Issue by drugo72** [cetic/6lbr#111]
Am I right if I'd say that this serial protocol is not SLIP at all? SLIP only supports sending IPv4 packets.
This is just a custom protocol whose framing resembles the SLIP one. Isn't this name misleading?

By reading the Wiki and looking at ```native-rdc.c``` I learn that 6lbr runs the MAC.
What does this mean? Is the CSMA-CA algortithm implemented in software by the 6lbr instead of the radio? It's impossible to do this over a serial line.

**Comment by laurentderu** [comment]
The serial protocol is based on SLIP frame format and has several extension, and therefore not SLIP compatible. The name is historical and widely used in the Contiki community.

The 6LBR runs a part of the CSMA layer, namely the retransmission, the CCA part is done by the radio driver in the radio module. But if needed the CSMA layer can be completely handled by the radio module, the 6LBR having only a transparent MAC layer.
