### ISSUE TITLE
Ethernet IP address autoconf not working

### ISSUE THREAD

**Issue by sotos183** [cetic/6lbr#114]
I am using 6lbr on an Ubuntu VM and more specifically I am running the example "make launch-6lbr-router-1-cooja". I have run the following configuration commands:

```
sysctl -w net.ipv6.conf.eth0.accept_ra=1
sysctl -w net.ipv6.conf.eth0.accept_ra_rt_info_max_plen=64
```

as my router supports RA and has been enabled (I have set the O flag 'on' and the M flag 'off').

I also do not have changed the "cooja-1-router.conf" configuration file.
Finally, I have done the following configuration through the 6lbr webserver:

```
Eth network prefix: aa:bb:cc:dd::
Eth network prefix length: 64
Eth IP address: ::
Eth default route: [The LAN IPv6 of my router]
Eth IP address autoconf: True
```

where aa:bb:cc:dd is the prefix deligation from my ISP.

My main problem is that I cannot ping the 6lbr webserver even from localhost (that's not the case when I set the Eth IP address autoconf to False).
The other problem is that when autoconfiguration of Ethernet IP is True the 6lbr address has always the same suffix, which is in the following format aa:bb:cc:dd:1:ff:ff01:101. Is that normal?

How can I configure the 6lbr to get a IPv6 address from my router in order to be able to access it from outside of my LAN?

**Comment by laurentderu** [comment]
(Sorry, we're purging the backlog slowly...)

The demo 'launch-6lbr-router-1-cooja' starts 6LBR in Router mode, which means the prefixes are manually configured in 6LBR and not auto configured. To use the auto configuration of the prefix, you must use the SmartBridge mode.
