### ISSUE TITLE
using RaspberryPi SPI bcm2835 Library, error exit code 139.

### ISSUE THREAD

**Issue by YinxuWang** [cetic/6lbr#117]
I am trying to modify slip-radio from uart to spi. I am using RaspberryPi SPI bcm2835 Library, but I found once I call bcm2835 spi libary's "bcm2845_spi_begin()", the program crashed and exited with code 139.

Anyone has idea?

Thanks.
Yinxu

**Comment by laurentderu** [comment]
We never used bcm2835 library, so we can not help much, it looks like a segmentation fault, either due to a missing initialization or corrupted data.
