### ISSUE TITLE
Support for Atmel ATSAMR21G18A in slip radio mode

### ISSUE THREAD

**Issue by akshat48** [cetic/6lbr#119]
Hi,
Does the 6lbr supports the Atmel ATSAMR21G18A in slip radio mode?
Or any pointers on how to port the code ?

I am planning to use 6lbr on Rpi2 with SAM R21 Xplained Pro Evaluation Kit working as slip radio.

Thanks,
Akshat

**Comment by laurentderu** [comment]
As long as Contiki does not support ATSAMR21G18A, 6LBR will not support it.
