### ISSUE TITLE
How to use 6lbr on an IPv4 network

### ISSUE THREAD

**Issue by serdarkose** [cetic/6lbr#120]
Hi,

Here is my set-up.

- CC26xx as a sensor module: has aaaa::xx address

CC2538 as a slip-radio: has aaaa::xx address

RaspberrPi is the edge router: wlan0 interface has a public IPv4 addr,and use "router" mode of 6lbr
![image](https://cloud.githubusercontent.com/assets/8748322/12725083/4229ba9a-c911-11e5-93f6-c4429eb8704b.png)

I am very confused how to access CC26xx nodes (aaaa::xx) from the server side?

Referring  processors.wiki.ti.com/.../Cc26xx_sw_examples , I installed Wrapsix on the RPI. What end address do I need to write when I send a UDP packet from the server/computer? Do I need to use Wrapsix or a different tunneling solution?

Second question: How can I use 6lbr under an Access Point that assigns private IPv4 addr (and doesn't support IPv6)? In that case, how can I access to the sensors?

**Comment by laurentderu** [comment]
WrapSix allows only communication from the IPv6 network to a IPv4 network, not the other way. The NAT64 functionality integrated in the develop branch of 6LBR allows static configuration of NAT64 mapping and so allows IPv4 to IPv6 communication.

For you second question, you can also use the integrated NAT64 to access 6LBR and the nodes using IPv4.

Note: the documentation for NAT64 is yet lacking...

**Comment by laurentderu** [comment]
NAT64 is now fully functional and the documentation is available here https://github.com/cetic/6lbr/wiki/NAT64
