### ISSUE TITLE
6lbr & mosquitto on one host 

### ISSUE THREAD

**Issue by Tux-007** [cetic/6lbr#121]
Hi, 

I'm running 6lbr as router with standard configuration [bbbb::100] on eth0 and [aaaa::xxx] on 6LoWpan side. I've also installed mosquitto. I've added ipv6 address [bbbb::102] to eth0. If I change in matt_client.c the broker ip to [bbbb::102] I get no packets from the sensor network. I've also tried to get it work with an NAT64 tool like wrapsix… no chance. Is there a way to get 6lbr and mosquitto get running on one linux server? 

Many thanks, 
Tux

**Comment by laurentderu** [comment]
The localhost should be accessible from the WSN, check if eth0 is bridged with tap0 and that the interface is properly configured (see /etc/6lbr/interfaces.dhcp.example)
