### ISSUE TITLE
6lbr didn't assign an ipv6 address for the network interface

### ISSUE THREAD

**Issue by rafaeldelucena** [cetic/6lbr#124]
Hi,

I'm followed the [TI CC26XX Example](http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples) and I found some issues on the 6LBR usage.

My border router consists of a SmartRF06EB+CC13xxEM burned with slip-radio and instead of a BeagleBone, I am using an Linux desktop with Debian 8 (jessie).

My configurations and log from the applications are shown bellow:

6lbr configuration file (https://gist.github.com/anonymous/a61c10c689ce82feb792)
6lbr output (https://gist.github.com/rafaeldelucena/2c644d189400c34457e2)

My ifconfig output, shown the eth0 network interface without an ipv6 address, with bbbb:: prefix https://gist.github.com/rafaeldelucena/03163fe81c75a8c6c77e

And this line is a serious issue?
```
2016-01-12 15:12:13.882860: ERROR: SLIP: Unknown command
```

I forgot something?

Thanks

**Comment by akshat48** [comment]
Hi rafaeldelucena,

The issue that you are facing may be solved by looking at the following post:

https://github.com/cetic/6lbr/issues/109

I solved a similar issue on RPi2  by following the above

Thanks,

**Comment by laurentderu** [comment]
The 'ERROR: SLIP: Unknown command' line usually means that the slip-radio does not support the set-channel command, so you're stuck with the default channel hardcoded in the firmware.

About your interface configuration, see : https://github.com/cetic/6lbr/wiki/6LBR-Connection
