### ISSUE TITLE
On Ubuntu;I can't visit the [bbbb::100]website through another pc

### ISSUE THREAD

**Issue by limotkl** [cetic/6lbr#129]
Now I can run 6lbr as a RPL ROUTHER on unbuntu and I can see the [bbbb::100]webset on the pc which runs 6lbr but i can't see the  bbbb::100 through another pc(my laptop) , I think it's something about IPv6 setting, the two computers are in the same subnet. 
Can you tell me how can I visit the [bbbb::100] through another pc(with windows os)? Thank you very much!

**Comment by laurentderu** [comment]
If the other pc has a bbbb::something address and you can't contact 6LBR, either your tap0 interface is not bridged with bR0 or you most probably have the multicast snooping issue, see  /etc/6lbr/interfaces.static.example

**Comment by limotkl** [comment]
Problem solved. I failed to bridge tap0 with br0. After I amended  /etc/network/interfaces it works.
Does it work in the same way with /etc/6lbr/interfaces.static.example?

**Comment by laurentderu** [comment]
Its the same way for static and dhcp, the only difference is the address configuration of the host. I will clarify the documentation.

**Comment by limotkl** [comment]
Thank you very much !
