### ISSUE TITLE
How to use 6lbr  to send data over cloud.

### ISSUE THREAD

**Issue by tarungarg15** [cetic/6lbr#132]
Currently I am able to use 6lbr stack to send data only to intranet. But I want to send data over the internet. Could you please suggest how can I do ?.

**Comment by laurentderu** [comment]
If you have IP6 connectivity, you can configure the peer router to your own router and the sensor can send their data directly.
If you don't have IPv6 connectivity, you can either use the integrated NAT64 functionality available on the develop branch, or use a service like gogoc or wrapsix

**Comment by tarungarg15** [comment]
Can I get same working example from Contiki ?.

**Comment by laurentderu** [comment]
6LBR is based on Contiki and should support any nodes running contiki, provided they use the same radio configuration (channel, pan id, rdc, ...)

**Comment by tarungarg15** [comment]
Thanks a lot I will check

On Mon, Mar 14, 2016 at 2:54 PM, Laurent Deru <notifications@github.com>
wrote:

> 6LBR is based on Contiki and should support any nodes running contiki,
> provided they use the same radio configuration (channel, pan id, rdc, ...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cetic/6lbr/issues/132#issuecomment-196220325>.
>



-- 




*Best Regards,Tarun Kumar Agarwal888-4334-625 (MO)*

**Comment by weijian19391** [comment]
@laurentderu Can i ask how do you configure the peer router to my own router?

**Comment by laurentderu** [comment]
This is on the Network configuration page, see : https://github.com/cetic/6lbr/wiki/LAN

**Comment by weijian19391** [comment]
@laurentderu Pardon me for being new to networking, it states that "Address of the Peer Router (or Default Router, or Gateway) of the LAN Network. ". May i know if this address needs to be one that is prefixed with bbbb?

**Comment by laurentderu** [comment]
The peer router address is not the address of your 6LBR, it's the link-local IPv6 address of your Internet Gateway or LAN router.

Note that if you want to have internet connectivity you have to change aaaa:: and bbbb:: prefixes are they will be rejected by your ISP, they are for demo only.

**Comment by weijian19391** [comment]
Oh i see. Are there any restrictions on what the prefixes should be?

**Comment by laurentderu** [comment]
Actually you must use the IPv6 prefix your ISP or your network admin gave you, or your packet will not be routed.

**Comment by weijian19391** [comment]
oh. Okie! thank you!

**Comment by dana555a** [comment]
hello there im trying to do the same hing but my network has Raspberry pi running 6lbr and cc1310 with slip radio as gateway. whith these settings how can i connect to cloud ?
