### ISSUE TITLE
NAT64 Configuration

### ISSUE THREAD

**Issue by sakitten123** [cetic/6lbr#133]
The develop branch is said to contain a NAT64 functionality.
However, I can't find any documentation on this and how to configure it.
Can you assist me in how and where the configuration is done? 

Thank you!

**Comment by laurentderu** [comment]
I have updated the NAT64 functionality recently, it is now stable. I will write the documentation soon :)

**Comment by laurentderu** [comment]
A short documentation is now available here https://github.com/cetic/6lbr/wiki/NAT64
