### ISSUE TITLE
About the platform

### ISSUE THREAD

**Issue by limotkl** [cetic/6lbr#137]
Hello, I want to use 6LBR on our own platform, and something need to be down to make it work, but there are too many code, I would like to know which documents are related to platforms,then I can figure out how to change them to make it work. Thank you very much.

**Comment by laurentderu** [comment]
It depends if your platform is Linux based or bare metal. If it's Linux based, you should make it work only by modifying the configuration files (in /etc/6lbr mainly).
If it's bare metal, first of all, your platform must be supported by Contiki. Then you must create the platform specific code in 6LBR (examples/6lbr/platform), the easiest way is to look at what it's done for CC2538.
