### ISSUE TITLE
Unable to access the web server thus data on the sensortag mote

### ISSUE THREAD

**Issue by drako65** [cetic/6lbr#151]
Hi Guys,
I am setting up a 6lowpan WSN, with three sensor tags.
Two have cc26xx-web-demo firmware from contiki source.
The other sensortag acts as a slip radio on raspberry pi.
I followed the guide here: http://blog.resens.net//post/Contiki-6LowPAN-Wireless-Sensor-Network-using-SensorTag
but for my case I was unable to get data from sensortags through web.
How to I setup routing in 6lbr to I can ping or http to the nodes?
The guide https://github.com/cetic/6lbr/wiki/6LBR-Connection
doesn't seem to work.
Thanks for your help.

**Comment by laurentderu** [comment]
Did your contiki source is from before of after mid-march ? If after, you need to change the default 6LoWPAN context from aaaa:: to FD00:: in 6LBR (you need the latest development snapshot to do that)

**Comment by drako65** [comment]
after mid march, YES IT WORKS! 
Thank you very much.! I've been working for this for two weeks.
