### ISSUE TITLE
Can contiki mote get real-world time?

### ISSUE THREAD

**Issue by wufucious** [cetic/6lbr#166]
In my project, all sensors need to know real-world time, say "dd/mm/year, 12:12", when they produce and store data. Any suggestion? Examples?

From my pointof view, all Contiki time library is usefulness because none of them are designed to get real-world time value. Does 6lbr provide such function?

**Comment by laurentderu** [comment]
No, there are no time service in 6LBR. But you could use NTP to sync your mote, I believe there is a lightweight implementation for contiki available.
