### ISSUE TITLE
/var/log/6lbr.ip is unassigned  

### ISSUE THREAD

**Issue by rohitsivakumar** [cetic/6lbr#167]
If 6LBR config is moved to ROUTER mode, the 6lbr ip gets assigned as bbbb::100 but as soon as you configure the 6lbr.conf to mode SMART-BRIDGE, the 6lbr ip is not assigned it as shows ::

Why is this happening?

6lbr.conf (Nothing is changed except the mode as ROUTER or SMART-BRIDGE).
(here is my SMART-BRIDGE config)

```
#The full list of parameters and their meaning can be found in 6lbr.conf.example

#MODE=ROUTER
MODE=SMART-BRIDGE
#MODE=RPL-RELAY
#MODE=FULL-TRANSPARENT-BRIDGE
#MODE=NDP-ROUTER
#MODE=6LR
#MODE=RPL-ROOT

RAW_ETH=0
BRIDGE=1
CREATE_BRIDGE=0
DEV_BRIDGE=br0
DEV_TAP=tap0
DEV_ETH0=eth0
RAW_ETH_FCS=0

DEV_RADIO=/dev/ttyACM0
BAUDRATE=115200

LOG_LEVEL=3 #INFO and above only
```

In smart-bridge mode, why is the 6lbr not having an ip assigned?

```
pi@bananapi /var/log $ cat 6lbr.ip
::

my radvd service and 6lbr will both run on the same hardware. What should be my radvd configuration?
```

**Comment by laurentderu** [comment]
The Router mode has default addresses prefconfigured, on the other hand in SmartBridge mode, 6LBR uses the existing network configuration to configure itself. If you don't already have an IPv6 router on your network, 6LBR will stay unconfigured (hence the :: in 6lbr.ip)
