### ISSUE TITLE
Release bundles for 1.4.0 missing or links broken

### ISSUE THREAD

**Issue by g-oikonomou** [cetic/6lbr#180]
Many (all) links to 1.4.0 bundles are broken (HTTP error 404)

https://github.com/cetic/6lbr/wiki/Releases#6lbr-140-packages

**Comment by laurentderu** [comment]
Something seems broken in the wiki, I can see the commit adding the new files in the history but when I try to open the commit, github can't find it anymore...

**Comment by laurentderu** [comment]
It turns out it was a stupid mistake, the version number was the letter 'O' instead of the cypher '0'...
