### ISSUE TITLE
Bug in contiki-cooja-main.c in contiki-merge branch

### ISSUE THREAD

**Issue by manuwsn** [cetic/6lbr#189]
In the contiki_init() :

#if NETSTACK_CONF_WITH_IPV6
  /* IPv6 CONFIGURATION */
 {
...
#if !UIP_DS6_NO_STATIC_ADDRESS
   ...
  }
#endif
#endif /* NETSTACK_CONF_WITH_IPV6 */

Should be : 

#if NETSTACK_CONF_WITH_IPV6
  /* IPv6 CONFIGURATION */
 {
...
#if !UIP_DS6_NO_STATIC_ADDRESS
   ...
#endif 
}
#endif /* NETSTACK_CONF_WITH_IPV6 */

**Comment by laurentderu** [comment]
Thanks for reporting, it's now fixed in the latest version of the branch.
