### ISSUE TITLE
Issue compiling 6lbr on Debian Jessie for BeagleBone 

### ISSUE THREAD

**Issue by rdeterre** [cetic/6lbr#190]
I've tried to follow the instructions to install 6lbr from source on Debian, and it seems that the 6lbr.service file does not get installed. Should this file be installed in `make install` and `make plugins-install`? Using the pre-compiled .deb file, there is no problem.

**Comment by laurentderu** [comment]
The install documentation was incomplete, you have to run the following command to install the init.d script :

    update-rc.d 6lbr defaults

Previously it was done in the make install command but it was conflicting with package creation.

**Comment by rdeterre** [comment]
Understood, thanks!
