### ISSUE TITLE
connecting contiki websense to 6lbr

### ISSUE THREAD

**Issue by marcomilazzo** [cetic/6lbr#195]
Dear Sir
i'm using 6lbr and sky and it works fine
i would like to use the contiki  websense in the ipv6 example dir
6lbr does see the node but i doesen't connect to the route
i did add  
# define NETSTACK_CONF_MAC   csma_driver
# define NETSTACK_CONF_RDC   nullrdc_driver
# define RF_CHANNEL          26

but still nothing
![image](https://cloud.githubusercontent.com/assets/15695459/16147881/4c7a57b2-3486-11e6-9bfd-82be53bf62c6.png)

What should i do ?
thank's
marco

**Comment by laurentderu** [comment]
The 'Last seen' value is not troublesome if there is no traffic from/to your node. Can you ping the node from your PC ? if not, it means your route towards the WSN are not properly configured, see https://github.com/cetic/6lbr/wiki/6LBR-Connection

**Comment by marcomilazzo** [comment]
Hi Laurent 
thank's a lot for the response
So there is nothing missing in the normal web-sense of contiky?
But the point is that it doesn't form the node tree ?
This is way i think there is something missing
I also tried the contiki udp client server and it workk
6lbr does see the node but no tree !
what am i missing?
thank's again
marco

**Comment by laurentderu** [comment]
If you mean the tree in the web server page, it's normal. You need a small application on your node to periodically send to 6lbr the information about the node's current parent. 6LBR by itself can not infer this information.

**Comment by marcomilazzo** [comment]
hi
can you tell me what application?
do you have an example?
thank's marco

**Comment by marcomilazzo** [comment]
Also
I'm using the cc2530 . is there a way to compile 6lbr-demo for this chip?
Marco

**Comment by laurentderu** [comment]
The CC2530 is quite a limited platform and we don't plan to support it

**Comment by fzy-Line** [comment]
I am using CC2538dk, and I also meet the same question. Have you solved it yet? Thanks!
