### ISSUE TITLE
mtarch.c: obsolete POSIX functions

### ISSUE THREAD

**Issue by leojrfs** [cetic/6lbr#209]
setcontext (ucontext) were obsolete on POSIX.1-2004 and on POSIX.1-2008 they were removed. 
They are not provided in C libs like uclibc and musl, so 6lbr does not compile.
As far as I can understand, 6lbr does not use mtarch.c. So, if removed, it compiles and works okay.

Is this a mainstream problem? You want to keep this for any special reason? What are your thoughts on this?

For now im using a [patch](https://github.com/leojrfs/packages/blob/master/net/6lbr/patches/100-remove-ucontext.patch) to make it compile in openwrt as a workaround.

**Comment by laurentderu** [comment]
This has been removed in Contiki-NG (Finally !).
