### ISSUE TITLE
6LBR not starting on BeagleboneGreen Wireless

### ISSUE THREAD

**Issue by amruthabellave** [cetic/6lbr#210]
Hi,

We have installed 6LBR on beaglebone green and a TI sensor tag has been configured as a SLIP Radio. 
The log file has a FATAL Error. I am attaching the log details. Any insight or corrections on this error will be very helpful. Thanks in advance!!
![image](https://cloud.githubusercontent.com/assets/20762183/17281121/601eee1e-574e-11e6-98aa-45dc4a7e98ee.png)
![image](https://cloud.githubusercontent.com/assets/20762183/17281126/77f2cb50-574e-11e6-867a-ee7ffb35db06.png)

**Comment by chenek** [comment]
Do you use WIFI connect to Internet? If so, try to use Ethernet cable and test again.
