### ISSUE TITLE
6lbr not starting on Beaglebone Green Wireless.

### ISSUE THREAD

**Issue by supriya20** [cetic/6lbr#212]
Hi,

I am trying to build an Edge Router with a SLIP radio using CC2531 dongle and 6LBR installed on BeagleBone Green Wireless to connect to a 6LoWPAN Network.

I have flashed the CC2531 with contikimac hex file and installed 6LBR on to my BBG Wireless following the steps mentioned in the link [https://github.com/cetic/6lbr/wiki/Other-Linux-Software-Configuration] and on [http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples]. When I start 6LBR on BBG, service will be started but the webpage https://[bbbb::100] is not opening. When I checked the log file 6lbr.log I found that 6lbr service is started but it is failing due to a fatal error: "FATAL: TAP: ioctl() : No such device". Contents of my log file and the output of few of the commands are as below:

/dev

![image](https://cloud.githubusercontent.com/assets/20494027/17459285/65a4498c-5be6-11e6-918c-cbbc51181b71.png)

ifconfig

![image](https://cloud.githubusercontent.com/assets/20494027/17459289/945afdd4-5be6-11e6-83b6-8dc4796597ea.png)

lsusb

![image](https://cloud.githubusercontent.com/assets/20494027/17459293/a3c1091c-5be6-11e6-8aae-d81c44687ee4.png)

sudo lsusb -v

![image](https://cloud.githubusercontent.com/assets/20494027/17459294/b29d69c6-5be6-11e6-92db-d787cea4b276.png)

nvm.dat file

![image](https://cloud.githubusercontent.com/assets/20494027/17459298/be76cb66-5be6-11e6-9134-94c6a348fb36.png)

6lbr.log

![image](https://cloud.githubusercontent.com/assets/20494027/17459301/f4a4f21c-5be6-11e6-8a11-2f971f73f805.png)

6lbr.err

![image](https://cloud.githubusercontent.com/assets/20494027/17459303/feb269e2-5be6-11e6-80e2-0fded0f84196.png)

6lbr.conf

![image](https://cloud.githubusercontent.com/assets/20494027/17459313/57a7dfe6-5be7-11e6-9604-d95629bd15d8.png)

Please help me out with this.

Thanks in Advance!!

Supriya

**Comment by chenek** [comment]
I suppose you use WiFi. If you switch to use Ethernet cable, it should work fine.
