### ISSUE TITLE
CC2538 6lbr-demo mote rebooting with TINYDTLS

### ISSUE THREAD

**Issue by Devesh24** [cetic/6lbr#214]
Hello Guys,
                    i am running 6lbr-demo with coap_server and tiny_dtls on cc2538 , and as a client  i am using californium.tools , but when i try to discover the well-known core the 6lbr-demo mote keeps rebooting after receiving client hello and sending confirmation for hello, 6lbr-demo logs are below

Contiki-contiki-merge-20160622-28-g56f8407
TI SmartRF06 + cc2538EM
 Net: sicslowpan
 MAC: CSMA
 RDC: nullrdc
 Channel: 26
 PAN-ID: abbb
Rime configured with address 00:12:4b:00:04:0e:ff:5d
Starting CoAP-18 receiver...
Started DTLS retransmit process
COAP-DTLS listening on port 5684
CoAP push started
CoAP server started
RD client started
dtls_handle_message: PEER NOT FOUND
peer addr: :45561
got packet 22 (94 bytes)
DEBG receive header: (u bytes):
00000000 16 FE FD 00 00 00 00 00  00 00 00 00 51 
DEBG receive unencrypted: (u bytes):
00000000 01 00 00 45 00 00 00 00  00 00 00 45 FE FD 57 CE 
00000010 BB A1 BC 4D D8 1A EC 90  08 24 99 BA 0A 52 AF EB 
00000020 EA E6 C4 1F BA D5 00 C6  49 29 EA D8 79 D6 00 00 
00000030 00 02 C0 A8 01 00 00 19  00 0A 00 08 00 06 00 17 
00000040 00 18 00 19 00 0B 00 02  01 00 00 14 00 03 02 00 
00000050 02 
received handshake packet of type: client_hello (1)
handle handshake packet of type: client_hello (1)
DEBG create cookie: (u bytes): 354C551C4C333503353AC6B1F5D5ED03
DEBG compare with cookie: (u bytes): 
cookie len is 0!
send handshake packet of type: hello_verify_request (3)
DEBG send header: (u bytes):
00000000 16 FE FD 00 00 00 00 00  00 00 00 00 1F 
DEBG send unencrypted: (u bytes):
00000000 03 00 00 13 00 00 00 00  00 00 00 13 
DEBG send unencrypted: (u bytes):
00000000 FE FD 10 35 4C 55 1C 4C  33 35 03 35 3A C6 B1 F5 
00000010 D5 ED 03 
server hello verify was sent
dtls_handle_message: PEER NOT FOUND
peer addr: :45561
got packet 22 (110 bytes)
DEBG receive header: (u bytes):
00000000 16 FE FD 00 00 00 00 00  00 00 01 00 61 
DEBG receive unencrypted: (u bytes):
00000000 01 00 00 55 00 01 00 00  00 00 00 55 FE FD 57 CE 
00000010 BB A1 BC 4D D8 1A EC 90  08 24 99 BA 0A 52 AF EB 
00000020 EA E6 C4 1F BA D5 00 C6  49 29 EA D8 79 D6 00 10 
00000030 35 4C 55 1C 4C 33 35 03  35 3A C6 B1 F5 D5 ED 03 
00000040 00 02 C0 A8 01 00 00 19  00 0A 00 08 00 06 00 17 
00000050 00 18 00 19 00 0B 00 02  01 00 00 14 00 03 02 00 
00000060 02 
received handshake packet of type: client_hello (1)
handle handshake packet of type: client_hello (1)
DEBG create cookie: (u bytes): 354C551C4C333503353AC6B1F5D5ED03
DEBG compare with cookie: (u bytes): 354C551C4C333503353AC6B1F5D5ED03
found matching cookie
creating new peer
dtls_new_peer: :45561
Contiki-contiki-merge-20160622-28-g56f8407
TI SmartRF06 + cc2538EM
 Net: sicslowpan
 MAC: CSMA
 RDC: nullrdc
 Channel: 26
 PAN-ID: abbb
Rime configured with address 00:12:4b:00:04:0e:ff:5d
Starting CoAP-18 receiver...
Started DTLS retransmit process
COAP-DTLS listening on port 5684
CoAP push started
CoAP server started
RD client started

**Comment by Gr3yh0und** [comment]
Did do manage to fix this issue @Devesh24 ? I've got a similar one...
