### ISSUE TITLE
Contiki with CC1310

### ISSUE THREAD

**Issue by mario9876** [cetic/6lbr#225]
Hi I'm new on this job. I started working with Contiki, the CC1310 with SmartFR06EB and Raspberry. I'm trying to load the border router, but as soon as I type "sudo service 6lbr start" does not open my browser with the address bbbb :: 100. Can someone help me?

**Comment by ronnie1233** [comment]
Open your log files i can identify where you are going wrong . Do you write nvm.dat in the channel 25 .

**Comment by mario9876** [comment]
How?

**Comment by mario9876** [comment]
Ok, you have some guide that can be followed for the installation of contiki?

**Comment by ronnie1233** [comment]
The installation are avaliable on Github . 

- use cd /var/log 
after that use sudo nano 6lbr.log  . You will be able to generate log files

**Comment by ronnie1233** [comment]
http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples

This is the best installation guide .
