### ISSUE TITLE
Unable to access the Internet from the WSN node through IPv4 internet connection.

### ISSUE THREAD

**Issue by vad32m** [cetic/6lbr#229]
Hi, everyone. Due to lack of experience with computer networking I ask for your help. For past few days I have been trying to setup 6lowpan network and connect it to the Internet, for my wireless nodes to be able to act as HTTP clients. Desired topology is pretty simple:
![connection](https://cloud.githubusercontent.com/assets/5807480/21058734/045aecd4-be48-11e6-93f0-dd2c7e4d2376.png)
I downloaded InstantContiki VM and installed 6lbr to this VM. As my setup is experimental, I used COOJA to simulate WSN:
![cooja_start](https://cloud.githubusercontent.com/assets/5807480/21058810/786d98f6-be48-11e6-8c38-b89184ec9609.png)
After 6lbr service is launched my ifconfig output looks like this:
![ifconfig](https://cloud.githubusercontent.com/assets/5807480/21059810/f0f3aa14-be4c-11e6-880a-4ebda98ce690.png)
One of my nodes acts like slip-radio while others are flashed with udp-example firmware and modified HTTP example firmware. In my understanding, after 6lbr is properly configured and launched, my HTTP-example node should be able  to resolve hostname "www.contiki-os.org", but even after I launch 6lbr daemon, it cant resolve that hostname. 
![cooja_weird_arrow](https://cloud.githubusercontent.com/assets/5807480/21059094/9b1415d2-be49-11e6-84f5-3c514de0adba.png)
As you may see from the picture, udp client examples work OK, but HTTP-example node fails with resolving hostname. All nodes are visible in 6lbr web interface.
![6lbr_sensors](https://cloud.githubusercontent.com/assets/5807480/21059538/7eecefc6-be4b-11e6-8c8d-8142f3fafb63.png)
Another task I can't handle is configuring IP64, which is essential for internet connectivity. Can anyone give me advice on how to do that. My IP64 config looks like this:
![6lbr_config](https://cloud.githubusercontent.com/assets/5807480/21059558/947419be-be4b-11e6-976a-594ccb8c98ba.png)
But from web interface I see, that there are some problems with IP64 connectivity:
![6lbr_inf](https://cloud.githubusercontent.com/assets/5807480/21059644/2327c778-be4c-11e6-886a-c115b418703f.png)
![6lbr_status](https://cloud.githubusercontent.com/assets/5807480/21059648/2593ca8e-be4c-11e6-9f27-c7dd676b4986.png)
My log and config files:
[6lbrFiles.zip](https://github.com/cetic/6lbr/files/642873/6lbrFiles.zip)
Will appreciate any help or advice.

**Comment by ronnie1233** [comment]
Install Wrapsix to see your devices in IPV4 network . Recommend to see both Wrapsix since NAT64  service is nedded for this .

**Comment by laurentderu** [comment]
In simulation, the tap0 interface is not connected to any bridge at all, so you won't have internet connectivity by default. You have to see https://github.com/cetic/6lbr/wiki/6LBR-Interface-Configuration to enable the bridging mode and connect tap0 to eth0.

Another way is to use wrapsix as suggested by @ronnie1233 but I'm not familiar with it.

**Comment by vad32m** [comment]
@laurentderu thx for advice. I was trying to configure ebtables and iptables, but havent succeed with that. After I modified config file for using bridge between tap0 and eth0 interfaces, 6lbr succesfully retreived ipv4 adress over DHCP. 
RAW_ETH=0
BRIDGE=1
