### ISSUE TITLE
CoAp 6lbr

### ISSUE THREAD

**Issue by mario9876** [cetic/6lbr#230]
Hi, 
I have a problem with Coap on Mozilla Firefox. Practically, I changed all configurations to fit my device. I open the 6lbr server and clicking on COAP is my page, but puts us time to find the resources. How can I do?

**Comment by laurentderu** [comment]
This could happen if you are using bridged interfaces and your Ethernet device does not support bridging. You then have timeout as NDP messages are not forwarded properly.
