### ISSUE TITLE
6lbr on cc26xx/cc13xx?

### ISSUE THREAD

**Issue by vvzvlad** [cetic/6lbr#233]
I want to run 6lbr on the microcontroller TI cc26xx / cc13xx, not using it as a gateway 6lowpan <-> ipv6 (6lowpan-> slip-radio-> 6lbr-native-> lan or 6lowpan-> 6lbr-> ENC28J60), but simply as UDP server / client.

The system that I use now the scheme is marked as "OLD", what I would like to achieve as "NEW".
![6lbr](https://cloud.githubusercontent.com/assets/3315944/21472290/75d64154-cae3-11e6-921a-a268eaa44cb6.png)

Could you suggest, on the basis of an example I need to do my firmware to achieve the possibility of dismantling the UDP-package microcontroller as quickly as possible?

**Comment by laurentderu** [comment]
You can either comment out the ENC28J60 code or even use the rpl-root examples from Contiki.
