### ISSUE TITLE
running 6LBR on RPi and accessing the web page from same Rpi(INDIA)

### ISSUE THREAD

**Issue by rishi-electronut** [cetic/6lbr#238]
Hello,
I have set up 6LBR over RPi as mentioned in your Wiki Installation Guide.
Just to get the set-up going, I have been trying to run the 6LBR with configuration mentioned below:

6lbr.conf
`MODE=ROUTER
RAW_ETH=1
BRIDGE=0
DEV_BRIDGE=br0
DEV_TAP=tap0
DEV_ETH=eth0
RAW_ETH_FCS=0
DEV_RADIO=/dev/ttyUSB0
BAUDRATE=115200
LOG_LEVEL=3
`
Following command was issued on the RPi terminal.

`sudo service 6LBR start`

However, there is no 6lbr.ip file generated in /var/log/ directory as mentioned in your documentation. I am sure I have gone wrong in following the instructions.

**I also followed the below mentioned solution suggested by @sdawans to one of the issues.**
However, I only used 6LBR on RPi and virtual machine running ubuntu on another PC. I do not understand what is behaving as the IPv6 host in the below mentioned solution.

Hi again, when we released 6LBR, we concentrated on documenting RPi, BeagleBone and Econotag. Now, I have replayed a setup using the same configuration as you, and I can contact [bbbb::100] from the IPv6 host. Here is a summary of the steps. I will update the documentation soon. Please let me know if this works for you, I'm using Mint and Debian, it should be close to Ubuntu.

This is what I did:

On the 6LBR Host:

install bridge-utils

`sudo apt-get install bridge-utils`

download the 6lbr sources

compile /examples/ipv6/slip-radio and upload it to a mote (sky)
compile /examples/6lbr-demo/ and upload it to another mote (sky)
goto /examples/6lbr/

`make all_native
make tools
sudo make install`

create /etc/6lbr.conf from an example and edit it:

`MODE=ROUTER
RAW_ETH=0
BRIDGE=1
DEV_BRIDGE=br0
DEV_TAP=tap0
DEV_ETH=eth0
RAW_ETH_FCS=0
DEV_RADIO=/dev/ttyUSB0
BAUDRATE=115200
IFUP=/usr/lib/6lbr/6lbr-ifup
IFDOWN=/usr/lib/6lbr/6lbr-ifdown`

connect the 2 motes, make sure that the slip-radio mote is the same as what you put in DEV_RADIO
launch 6lbr

`sudo service 6lbr start`

On the other PC (directly connected by ethernet)

`sudo ip -6 addr add bbbb::101/64 dev eth0`

Why do we do this? Because you are on an isolated ethernet LAN without an external IPv6 Router. When we send RAs from the 6LBR in router mode, we intentionnally put the lifetime to 0 and announce WSN destinations explicity using the RIO option in RAs. In the next revision, we will give both options. In the meantime, it is expected that the IPv6 host accepts RIOs. I can explain this later, but it is irrelevant for now because we just want to contact the 6lbr webserver first.

Test

On the IPv6 host, try to access [bbbb::100] from a browser. It should display the 6lbr webserver correctly.

The logs

the end of your logs should contain this:

cat /var/log/6lbr.*
`-c /etc/6lbr/nvm.dat -s /dev/ttyUSB0 -t tap0 -R -B 115200 -U /usr/lib/6lbr/6lbr-ifup -D /usr/lib/6lbr/6lbr-ifdown -w /usr/bin/../lib/6lbr/www
Contiki-6lbr-1.0-rc0-11-g5e54897 started with IPV6, RPL
Rime started with address 1.2.3.4.5.6.7.8
MAC nullmac RDC br-rdc NETWORK sicslowpan
Opening nvm file '/etc/6lbr/nvm.dat'
NVM Magic : 2009
NVM Version : 0
WSN Prefix : aaaa:0000:0000:0000:0000:0000:0000:0000 
WSN IP address : aaaa:0000:0000:0000:0000:0000:0000:0100 
Eth Prefix : bbbb:0000:0000:0000:0000:0000:0000:0000 
Eth IP address : bbbb:0000:0000:0000:0000:0000:0000:0100 
Mode : 5f
Channel : 26
RAW/TAP init
********SLIP started on ``/dev/ttyUSB0''
opened device ``/dev/tap0''
tap0      Link encap:Ethernet  HWaddr 02:0a:0b:0c:0d:0e  
          inet6 addr: fe80::a:bff:fe0c:d0e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
br0       Link encap:Ethernet  HWaddr 02:0a:0b:0c:0d:0e  
          inet6 addr: fe80::a:bff:fe0c:d0e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
Fetching MAC address
TUN data incoming read:90
TUN data incoming read:46
TUN data incoming read:86
SLIP-DBG: cc2420_cmd: setting channel: 26
Got MAC
TUN data incoming read:78
TUN data incoming read:78
Low2Eth adding prefix
Eth MAC address :  06:00:14:6f:02:64 
Opening nvm file '/etc/6lbr/nvm.dat'
Tentative local IPv6 address  fe80:0000:0000:0000:0212:7400:146f:0264 
Tentative global IPv6 address (WSN)  aaaa:0000:0000:0000:0212:7400:146f:0264 
RA with autoconfig
Tentative global IPv6 address (ETH)  bbbb:0000:0000:0000:0000:0000:0000:0100 
Starting as ROUTER
UDP server started
CETIC 6LBR Started
SLIP: Sending 48
TUN data incoming read:101
Server received: '378 | fe80::0400:14ff:ff6f:0264' from aaaa::212:7400:1466:1fdb
Responding with message: Hello from the server! (1)
Server received: '378 | fe80::0400:14ff:ff6f:0264' from aaaa::212:7400:13b7:6d50
Responding with message: Hello from the server! (2)

On the 6LBR Host

`ifconfig
br0       Link encap:Ethernet  HWaddr 02:0a:0b:0c:0d:0e  
          inet6 addr: fe80::a:bff:fe0c:d0e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:583 (583.0 B)  TX bytes:4872 (4.8 KB)
eth0      Link encap:Ethernet  HWaddr d4:be:d9:14:00:ea  
          inet6 addr: fe80::d6be:d9ff:fe14:ea/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:242009 errors:0 dropped:0 overruns:0 frame:0
          TX packets:113681 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:182730238 (182.7 MB)  TX bytes:31001936 (31.0 MB)
          Interrupt:20 Memory:e6e00000-e6e20000 
tap0      Link encap:Ethernet  HWaddr 02:0a:0b:0c:0d:0e  
          inet6 addr: fe80::a:bff:fe0c:d0e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:467 errors:0 dropped:0 overruns:0 frame:0
          TX packets:529 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:54152 (54.1 KB)  TX bytes:47537 (47.5 KB)`

On the IPv6 Host

`sudo netstat -nr6
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
bbbb::/64                      ::                         UAe    256 0     0 eth0
fe80::/64                      ::                         U    256 0     0 eth0
::/0                           ::                         !n   -1  1   118 lo
::1/128                        ::                         Un   0   1     3 lo
bbbb::221:70ff:fed6:642/128    ::                         Un   0   1     1943 lo
fe80::221:70ff:fed6:642/128    ::                         Un   0   1     0 lo
ff00::/8                       ::                         U    256 0     0 eth0
::/0                           ::                         !n   -1  1   118 lo
ifconfig
eth0      Link encap:Ethernet  HWaddr 00:21:70:d6:06:42
          inet6 addr: bbbb::101/64 Scope:Global
          inet6 addr: bbbb::221:70ff:fed6:642/64 Scope:Global
          inet6 addr: fe80::221:70ff:fed6:642/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2106593 errors:0 dropped:0 overruns:0 frame:0
          TX packets:95283 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:414214840 (395.0 MiB)  TX bytes:8711929 (8.3 MiB)
          Interrupt:22 Memory:f6ae0000-f6b00000`
Please let me know if this works for you.

**Comment by laurentderu** [comment]
If I believe your log, you are using version 1.0-rc0 which quite old, where did you find it ?

Please upgrade to 1.4.1 or develop, which incidentally have the 6lbr.ip file as well as many bug fixes and new features :)
