### ISSUE TITLE
6lbr log

### ISSUE THREAD

**Issue by kameleon070** [cetic/6lbr#242]
Ok, so i've configured my network:

PC <-> PC with 6lbr <-> cooja network

On PC with 6lbr i want to RAW mode, what should i have on set on eth(or maybe another mode, i saw many issues with that but i think Raw is the best in this case because i only need to set NAT64)?

Are those extra files to configure?

I'm making sudo service 6lbr start, 6lbr is connecting with local host but i don't receive logs...

edit sorry for the topic

**Comment by laurentderu** [comment]
By default the log files are located in/var/log. You have 6lbr.log and 6lbr.err. This can be modified in your 6lbr.conf file, see https://github.com/cetic/6lbr/wiki/6LBR-Configuration-file
