### ISSUE TITLE
Interfacing 6LBR with a Simulated WSN (COOJA)

### ISSUE THREAD

**Issue by MrMikeyMouse** [cetic/6lbr#243]
Hi,

I'm running example. Everything is good because i can ping addresses from cooja but when i want to set ports to enjoy NAT64 i see this:

<img width="372" alt="zrzut ekranu 2017-01-16 o 08 42 29" src="https://cloud.githubusercontent.com/assets/25146362/21974647/3f55bbb4-dbc8-11e6-9d96-f3839dc372fb.png">

In my noode-config i have this:

<img width="325" alt="zrzut ekranu 2017-01-16 o 08 47 14" src="https://cloud.githubusercontent.com/assets/25146362/21974675/7187fb24-dbc8-11e6-8d41-f73e29098900.png">

What should i do?

**Comment by laurentderu** [comment]
Do you see parsing errors in 6lbr.log ? I believe you can not put on the same line the header for the node [...] and the parameter configuration name=...

**Comment by MrMikeyMouse** [comment]
It's just example, i don't see logs, hmmm. But many thanks I've corrected and now i have
<img width="324" alt="zrzut ekranu 2017-01-16 o 16 35 03" src="https://cloud.githubusercontent.com/assets/25146362/21989046/c25b1ce8-dc09-11e6-9f43-037aae6f46cf.png">

ok i have NAT64 on 192.168.52.2 and i my eth0  is set on 192.168.52.128 and i can ping my NAT64 but when i type [192.168.52.2:25000] and it's not working(i run http on my nodes it's working when i type http://[aaaa::202:2:2:2]/ i see "websense"] What i doing wrong?? :(

**Comment by laurentderu** [comment]
If NAT64 is configured properly and your Eth interface has a valid IPv4 configuration and your node has a HTTP server enabled, it should work without problem. Could you set the log level to 5 and see if you try to access your node that you have outgoing packets on the WSN ?
