### ISSUE TITLE
6lbr.ip file missing

### ISSUE THREAD

**Issue by jbartlett12026** [cetic/6lbr#249]
Hello,
    I am using 6lbr with the following demo: http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples
and I am not able to see the [bbbb::100] webpage. I looked at the 6lbr.ip file to see what was registered and the file is not there. Am I missing something here?

HW:  -Edge Router: Beaglebone Black with CC1310 LP as a slip radio --> flashed with slip-radio.bin
        -Mesh Nodes: CC1310 LP -->flashed with cc26xx-web-demo

Error file: Starting 6lbr
Log file: 
![image](https://cloud.githubusercontent.com/assets/12144692/22430243/2975186a-e6d3-11e6-85bc-48ad7a11621b.png)

**Comment by ronnie1233** [comment]
Did you set the RF Channel

**Comment by jbartlett12026** [comment]
If this is done in the nvm.dat file then yes, I specified it to be 25, which is what I also specified on the CC1310.

**Comment by jbartlett12026** [comment]
![image](https://cloud.githubusercontent.com/assets/12144692/22511968/10812a3e-e85d-11e6-9af8-4716220adb25.png)


This is what the COM port for the CC1310 LP is saying. It looks like an error for the RF channel??

**Comment by laurentderu** [comment]
@jbartlett12026 What is the content of your 6lbr.log file ? Looking at the output of the slip-radio, it seems the device is reseting constantly.

**Comment by jbartlett12026** [comment]
I think you're correct. I have tried rebuilding and keep getting the following. It keeps restarting right before specifying the channel. Any thoughts? I built from slip-radio using **make TARGET=srf06-cc26xx BOARD=launchpad/cc1310** 

![image](https://cloud.githubusercontent.com/assets/12144692/22517435/af78c564-e86e-11e6-991a-2fef4d926506.png)

**Comment by ronnie1233** [comment]
Yes you are on the right path here . It seems your slip radio does not  seem to  fetch BR-RDC  MAC address . Would recommend to look at  Project  config file .  If it is then it seems there is problem with ur submodule  in your RPI3 or BBB what ever you are using as border router .

**Comment by jbartlett12026** [comment]
@ronnie1233 
 It was a problem with the USB-UART power I was using, which was causing it to loop and not start the radio. Now it appears to work before the putty crashes. Thank you for your response!
