### ISSUE TITLE
6LR Node and ROUTER

### ISSUE THREAD

**Issue by ultrabalad** [cetic/6lbr#251]
Hi Experts,

I am having problem to connect between ROUTER (A) and 6LR (B). The network as follow:

PC-A -> slip-A ----- slip-B -> PC-B

PC-A IP
bbbb::a:bff:fe0c:d0e/64 Scope:Global
fe80::1ca4:e5ff:fe73:3ece/64 Scope:Link
bbbb::21c2:b4f7:4318:3a3c/64 Scope:Global

slip-A
bbbb::100
aaaa::212:7401:1:101
fe80::212:7401:1:101

slip-B
aaaa::212:7402:2:202 P A
fe80::212:7402:2:202 P A

PC-B IP
aaaa::300/64 Scope:Global (statically assigned)
fe80::a:bff:fe0c:d0e/64 Scope:Link

I'm able to ping from PC-A to slip-B successfully, but fail to PC-B which the public IP address I assign it static. My question is how to configure the 6LR node, so that PC-B will be able to ping to PC-A ?

Hope someone could help and advice me on this matter.

Thank you 
Jai

**Comment by laurentderu** [comment]
Sorry for the late reply :)

This setup can not work out of the box with a RPL network, the routing table built by the Router (PC-A) contains a route towards the 6LBR (Slip-B), however it does not contain a route towards PC-B (or any unknown other host).
There are several way to make this working, but it requires extra configuration (and testing as not everything has been fully validated).
If you don't need multi-hop, you can make this working simply using NDP-ROUTER mode and by adding manual routes between the two NDP-ROUTER or setting up the B host as a Transparent Bridge. I think there is another issue here that describe this configuration, but I can't find it right now.
Another possibility, but not tested, would for the 6LR to send also send proxy DAO for PC-B, but that would require the 6LR to learn the IP of PC-B and add it to the periodical DAO.
Another way would be to have a DAO with a full subnet.
Lastly, but that would require some extra coding too, would be to add a RIO option in the DIOs messages with a route for PC-B using 6LR address as next hop.
