### ISSUE TITLE
Problem setting up 6lbr in ubuntu 16.04

### ISSUE THREAD

**Issue by bharaththiruveedula** [cetic/6lbr#252]
Hi,

I am trying to follow the steps mentioned in [https://github.com/cetic/6lbr/wiki/COOJA-Interface](https://github.com/cetic/6lbr/wiki/COOJA-Interface), but while running "make cooja-small" I am getting the error like [https://gist.github.com/bharaththiruveedula/d6b62357696e3714c3d916c368e8ca70](https://gist.github.com/bharaththiruveedula/d6b62357696e3714c3d916c368e8ca70). But then I tried to continue to connect to lbr using "make launch-6lbr-router-1-cooja" and then clicked on "start" button, I got error [https://gist.github.com/bharaththiruveedula/0ea82c6d8c9e2b357df8b487d6df89e1](https://gist.github.com/bharaththiruveedula/0ea82c6d8c9e2b357df8b487d6df89e1) and then cooja closed by itself. 

I have tried manually setting "DEFAULT_PROJECTDIRS" in .cooja.user.properties, but the values are overriding everytime  we run make cooja-small. 

Any help regarding these issues?

**Comment by laurentderu** [comment]
I haven't seen that kind of issue recently. Are you using a 32 bits or 64 bits platform ? Cooja does not work well with 64 bits platforms. Also you seem to have strange warning while compiling, which compiler are you using ?
