### ISSUE TITLE
6lbr with API

### ISSUE THREAD

**Issue by MarCast** [cetic/6lbr#258]
Hi everyone, I have a 6lbr system all working. Now I would like implement the API. It's possible. Can someone help me? Thanks

**Comment by MarCast** [comment]
@laurentderu  @g-oikonomou

**Comment by laurentderu** [comment]
Sorry, I don't understand the question. Taking a wild guess, you should have a look at CoAP and LWM2M  examples.

**Comment by MarCast** [comment]
I would like to implement the CC26xx-web-demo/6lbr API. It is Possible? @laurentderu

**Comment by laurentderu** [comment]
It's possible, see http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples

**Comment by MarCast** [comment]
No, this article does not speak of the API.

**Comment by laurentderu** [comment]
I'm sorry, unless you clearly define what you mean by "API" no one is able to help you.
