### ISSUE TITLE
How to install  6lbr for openwrt（WRTnode2R）?&Where can i find the ipk code of 6lbr for openwrt?

### ISSUE THREAD

**Issue by SHshenb** [cetic/6lbr#263]

**Comment by SHshenb** [comment]
Where can i find the ipk code of 6lbr for openwrt?

**Comment by zubair-apece** [comment]
Hi, did you find the solution? I need to install 6lbr in openwrt too

**Comment by SHshenb** [comment]
I have installed 6lbr successfully ,but there still have some problem. How can i communicate with you to dicuss this problem and tell you how to isntall?

**Comment by zubair-apece** [comment]
Thanks for your quick response and willingness to help. my email is kzubair.bd@gmail.com
I would really be grateful to you if you guide me to do so. I suppose we can help each other about this.

**Comment by SHshenb** [comment]
I have sent a email for you.

**Comment by knowic** [comment]
What is the problem you have meet? Also,I have got the Openwrt run with wrtnode board, but I have not get RA message correct from Openwrt
. My mail is knowic@gmail.com ,would you please send me mail so that we can have some discussion about the issue.

**Comment by laurentderu** [comment]
I updated the OpenWRT documentation, see https://github.com/cetic/6lbr/wiki/OpenWRT-Installation
