### ISSUE TITLE
Q: Modifying RPL

### ISSUE THREAD

**Issue by omerfirmak** [cetic/6lbr#274]
Hello there,

If I use 6lbr as the border router and run cetic-6lbr-client.c on my 6lowpan nodes along side of my application code which just opens up some UDP sockets and transmits periodic data, is RPL used in this setup? Are my 6lowpan nodes aware of routing scheme, have access to RPL DAG?

I want to modify the RPL implementation of Contiki. What would be the best way to get in to that?

**Comment by laurentderu** [comment]
cetic-6lbr-client.c is just a demo application used to report the current parent of the node to the BR and do some PRR statistics.
By default 6LBR has RPL enabled and any RPL based node can connect to the BR
