### ISSUE TITLE
6lbr webserver lite

### ISSUE THREAD

**Issue by MarCast** [cetic/6lbr#285]
Hi everyone, I managed to connect my CC1310 5X5 with the ENC28J60 and i can ping [bbbb::100], the result is the 6lbr webserver-lite. Now I would like to connect a node to monitor how the CC26xx-web-demo. Is there a way?

**Comment by MarCast** [comment]
@laurentderu @g-oikonomou

**Comment by chenek** [comment]
I test to run  cc26xx-web-demo to join my LAUNCHXL-CC1310+ENC28J60 runing 6lbr Lite and it works without problem. The only revision I need to do is to change "#define RF_CORE_CONF_CHANNEL 25" to "#define RF_CORE_CONF_CHANNEL 26" in project-conf.h when I build cc26xx-web-demo.

**Comment by MarCast** [comment]
Where the genres of the file? Under Contiki or 6lbr?

**Comment by chenek** [comment]
I couldn't understand your question. genres of the file?
