### ISSUE TITLE
some question about slip-radio handle packet

### ISSUE THREAD

**Issue by zx2194023** [cetic/6lbr#286]
Hey,guys
I have one question about slip-radio. When client send 1000 packet to slip-radio and  send interval is 10ms.
but i see slip-radio only can handle 3 packet at most. when slip-radio have 3 packet , client doesn't send any packet until slip-radio send 3 packet  to border-router. i don't know what is going on. 
I want to modify code make skip-radio can handle more packet .

In " core/dev/slip.c " this code,i see slip-radio only can handle two packet 
this command out is in slip.c
/*
If begin != pkt_end we have a packet at [begin, pkt_end),
 * furthermore, if state == STATE_TWOPACKETS we have one more packet at
 * [pkt_end, end). If more bytes arrive in state STATE_TWOPACKETS
 * they are discarded.
*/

so ,i think  maybe can modify this code to make slip-radio handle more packet ,can someone give me some idea?  thanks.

**Comment by laurentderu** [comment]
If you are using the latest version of Contiki, or if you are compiling the slip-radio in 6LBR tree, you can increase the number of pending packet using the following configuration parameter :

    SLIP_CONF_BUF_NB

note that there is another limit of 16 pending packets between the BR and the slip-radio.
