### ISSUE TITLE
The dropped packets annoy, where they cause

### ISSUE THREAD

**Issue by steven3w** [cetic/6lbr#289]
Hi,

I have the 6lbr in BBB and set it as router with bridge=1, it works fine, except the dropped packets number in IP is pretty high and unsupported type in ICMP, in the Statistics tab on the web page.

I wonder what is the possible reason? Do these dropped packets will cause long term problem? It is a worry.

IP
Received packets : 78000
Sent packets : 33907
forwarded packets : 3172
Dropped packets : 9197
Wrong IP version or header length : 0
Dropped IP fragments : 0
Checksum errors : 0
Unsupported protocol : 0

ICMP
Received packets : 52815
Sent packets : 16879
Dropped packets : 8322
Unsupported type : 8322
Checksum errors : 0

TCP
Received packets : 4228
Sent packets : 3746
Dropped packets : 0
Checksum errors : 0
Ack errors : 0
Received RST : 6
retransmitted segments : 1
Dropped SYNs : 0
SYNs for closed ports : 6

UDP
Received packets : 5397
Sent packets : 5397
Dropped packets : 3193
Checksum errors : 0

NDP
Received packets : 2355
Sent packets : 4795
Dropped packets : 0

RPL
Memory overflow : 0
Local repairs : 0
Global repairs : 0
Invalid packets : 0
DIO timer resets : 3154
Parent switch : 0
Forward errors : 0
Loop errors : 0
Loop warnings : 1
Root repairs : 0

CSMA
Allocated packets : 0
Allocated neighbors : 0
Packet overflow : 0
Neighbor overflow : 0

Send packets : 25520
Received packets : 49090
Not acked packets : 34
Collisions : 287
Retransmissions : 319
Dropped packets : 2
Deferred packets : 0

RDC
Callback count : 0
Ack timeout : 0
Parse error : 0

SLIP
Messages sent : 25810
Messages received : 74900
Bytes sent : 2008626
Bytes received : 3690209

Steven Dong

**Comment by laurentderu** [comment]
Usually that means you have ICMPv6 multicast activity on your LAN that is not supported (and therefore dropped) by 6LBR. So, at first sight it's not a problem.
