### ISSUE TITLE
How to make MQTT message sent to IBM Bluemix using 6lbr Lite running on LAUNCHXL-CC2650

### ISSUE THREAD

**Issue by chenek** [cetic/6lbr#290]
I can run 6lbr Lite on LAUNCHXL-CC2650 + ENC28J60 and join another  LAUNCHXL-CC2650 running cc26xx-web-demo. I can access to sensor web page and coap server on cc26xx-web-demo. However, I cannot see MQTT messages sent to IBM Bluemix. I believe it's because 6lbr Lite doesn't include NAT64 capability. So, how to make MQTT message sent to IBM Bluemix using 6lbr Lite running on LAUNCHXL-CC2650?

**Comment by paishreeni** [comment]
I'm using srf06-cc2650. even I've the same issues.

**Comment by whu-inf** [comment]
Similar issue. And btw have you ever tried to access sensor webpage through WLAN, like,  using an android phone? My LAN-wired-PC has access to those webpages but my cellphone doesn't.
