### ISSUE TITLE
6lbr on RPI without slip

### ISSUE THREAD

**Issue by ffischer91** [cetic/6lbr#297]
Can I use this 6lbr only with slip?
I have an 802.15.4 adapter from openlab an would like to speak to the nodes over this.
In the ifconfig i already see lowpan0 device and i can ping to the nodes with it.

The question is, how i have to configure the 6lbr?
Can you give me some hints for the 6lbr.conf
My conf file at the moment:

MODE=ROUTER
RAW_ETH=0
BRIDGE=0
DEV_TAP=tap0
DEV_ETH=eth0

the /var/log/6lbr.log only shows:
Waiting for
Waiting for
Waiting for
Waiting for

**Comment by msolters** [comment]
Hi, not that I think there is much progress (??) but there is a similar (possibly identical, excepting driver completeness) issue here https://github.com/cetic/6lbr/issues/112
