### ISSUE TITLE
Failed to open /usr/lib/6lbr/plugins/lwm2.so

### ISSUE THREAD

**Issue by marguil** [cetic/6lbr#299]
When running the service on a  raspberry pi, I got in the 6lbr.log this error : 
could not open /usr/lib/6lbr/plugins/lwm2.so: /usr/lib/6lbr/plugins/lwm2.so: undefined symbol: native_config_add_callback.

**Comment by laurentderu** [comment]
This means the plugin and the 6LBR binary have not been compiled from the same source, do a make clean, make plugins-clean and do a fresh installation.
