### ISSUE TITLE
unable to see TI sensortag 2.0 from webpage

### ISSUE THREAD

**Issue by naivewong** [cetic/6lbr#307]
According to the link http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples i used beaglebone black, CC2531 USB dongle and CC2650 sensorTag. And i succeeded in accessing the website [bbbb::100] and i was able to see the sensorTag on [bbbb::100]/sensors.html.
 
Then i replaced the beaqglebone black with the raspberry pi and my raspberry’s version was 4.4.50-v7+. And after configuration i was able to access [bbbb::100] but i was not able to see the sensorTag on the website. I found a link https://github.com/cetic/6lbr/issues/92 on github and its problem was the same with me. But the version of his raspberry pi was older. I didn’t have file /etc/inittab and the content of /boot/cmdline.txt was different. Now i have no idea how to configure it. There are several relevant pictures.
Thank you for your attention!
    
   
![sensor1](https://user-images.githubusercontent.com/26733153/26873016-131de0dc-4bab-11e7-8973-2f4354987ab6.jpg)

 
![sensor2](https://user-images.githubusercontent.com/26733153/26873017-14962b0e-4bab-11e7-9cb3-2db6fa80eeba.jpg)

![sensor3](https://user-images.githubusercontent.com/26733153/26873021-17cbabbe-4bab-11e7-89fd-73a49423a5dc.jpg)

![sensor4](https://user-images.githubusercontent.com/26733153/26873023-19bf971e-4bab-11e7-934a-3e38c300e988.jpg)
![sensor5](https://user-images.githubusercontent.com/26733153/26873032-1bb68c9e-4bab-11e7-8816-22dfff638f16.jpg)
![sensor6](https://user-images.githubusercontent.com/26733153/26873035-1e88a074-4bab-11e7-8296-1f6771395da2.jpg)
![sensor7](https://user-images.githubusercontent.com/26733153/26873041-21822246-4bab-11e7-8992-c389df54ffc1.jpg)
![sensor8](https://user-images.githubusercontent.com/26733153/26873044-232308e0-4bab-11e7-891d-45749bead2f5.jpg)
![nvm](https://user-images.githubusercontent.com/26733153/26873050-26656ba6-4bab-11e7-8e27-99d8af4ccfb1.JPG)

**Comment by laurentderu** [comment]
If you remove console=serial0, 115200 from your cmdline.txt does it solve the issue ? Also, try with removing dwc_otg.speed=1

**Comment by naivewong** [comment]
I first removed console=serial0, 115200 and it didn't work. Then I removed dwc_otg.speed=1 and it still didn't work. Is the problem with Raspberry's version or 6lbr's version?

**Comment by naivewong** [comment]
@laurentderu I first removed console=serial0, 115200 and it didn't work. Then I removed dwc_otg.speed=1 and it still didn't work. Is the problem with Raspberry's version or 6lbr's version?

**Comment by laurentderu** [comment]
I forgot that there is another daemon span by the system to provide a console on the UART, you must disable it either using raspi-config or manually, see https://github.com/cetic/6lbr/wiki/RaspberryPi-Software-Configuration#specific-configuration-for-the-uart-based-radio

**Comment by Usman78930** [comment]
I am also facing the same issue. i am using raspbian stretch. Kindly help me fix this problem
