### ISSUE TITLE
Cannot access one of the "web" page of sensortag after starting my python web crwal program for a while

### ISSUE THREAD

**Issue by naivewong** [cetic/6lbr#312]
In order to get the sensors' data automatically, I wrote a python web crawler program to crawl these two "web" page of my two sensors. The program will access one sensor's 'web', crawl the data and store them in MySQL, then after 60 seconds, the program will change to another sensor. Although at first everything was fine, after a while I cannot access one of the sensor's web, sometimes 6387, sometimes a500... So I want to ask if there's any restriction on the accessing times of the 'web' of the sensors?
![6lbr1 5_1](https://user-images.githubusercontent.com/26733153/27513098-98cf7ad0-598c-11e7-8bde-d96c2e2d71ad.JPG)
![6lbr1 5_2](https://user-images.githubusercontent.com/26733153/27513099-999d770a-598c-11e7-9f1b-53ae85bf4f88.JPG)
![6lbr1 5_3](https://user-images.githubusercontent.com/26733153/27513100-9ba1099a-598c-11e7-9459-94ca4a0a8166.JPG)

**Comment by naivewong** [comment]
Or if there are some other ways to continually get the data?
Thank you.

**Comment by laurentderu** [comment]
Solved in 5b43e1011bf8b7b6039a5b1eb109c6b2b730845e
