### ISSUE TITLE
How to address sensors using multicast address from TAP0

### ISSUE THREAD

**Issue by lcharpenwi6labs** [cetic/6lbr#319]
Hello
I need to send multicast messages to my network.
I want to send the request directly from my linux like this:

_echo "ping" | nc -6u -w1 ffe1::abcb 8765_

I know the address is good as the operation works fine when it is done inside the 6lbr.

Also, I can send data to a unique sensor.
Like this:
_echo "PW:0" | nc -6u -w1 fd00::3232:3020:1000:2900 8765_

I use a TAP0 and a br0 interfaces

I forced the route:
route -6

_ff1e::abcd/128                 ::                         U    1024 0     0 tap0
ff1e::/64                      ::                         U    1024 0     0 tap0_

also tried this:
route -6

_ff1e::abcd/128                 ::                         U    1024 0     0 br0
ff1e::/64                      ::                         U    1024 0     0 br0_

The problem is that all the mulitcast packets directly go to eth0...
Why aren't they routed to br0 or Tap0?

Do you have any idea?
Any option I forget to set?

Thanks a lot

**Comment by laurentderu** [comment]
The multicast was not supported by 6LBR until very recently, you can use the feature-multicast branch to test it. (You might need to enable a multicast router, like mrd6, on your router to register the multicast routes advertised by 6LBR)
