### ISSUE TITLE
RPi 3 6lbr: contiki demo web server and coap doesn't run

### ISSUE THREAD

**Issue by jacekrz** [cetic/6lbr#320]
Hi
I have run 6lowpan lbr (RPi 3 debian 9) and contiki cc26xx-web-demo on cc1350 launchpad. From firefox  I can access bbbb:100 address, folds: sensors->sensors and sensors-Node tree But I can not open web server and coap and can not ping nodes from pc (from rpi - ok). 6lowpan lbr router is configured in Bridge Mode. Should I configure or install something else like route table or radvd etc.
Regards
JacekRz

**Comment by laurentderu** [comment]
This is solved in upcoming 1.4.2 and 1.5.0 releases.
