### ISSUE TITLE
how to 6lbr.log file size to be limitted

### ISSUE THREAD

**Issue by junwushi** [cetic/6lbr#321]
how to limit the 6lbr.log file size?, if 6lbr service has problem then the log file size will fill the whole disk size .

**Comment by laurentderu** [comment]
You can use logrotate to limit the size of the 6lbr log files. There is an example available in 6lbr/openwrt/logrotate.d/6lbr.conf

The file can be added to cron with for example the following line :

    01 * * * * logrotate /etc/logrotate.d/6lbr.conf
