### ISSUE TITLE
Not Able to Ping rest server sky mote or any other apllication...It showing list of nodes connected...but not communicating

### ISSUE THREAD

**Issue by appalanaidugollu** [cetic/6lbr#324]
Hi,

I am using Raspberry Pi(as edge router) and TelosB Sky mote or STM32 evaluation board  (as a slip radio). I have followed all the steps mentioned in 6lbr linux configuration page to configure my bbb as edge router. However I am not able to ping the ipv6 address bbbb::000, and getting web page. After that  If I want communicate with other motes like sky-web sense or rest server, it showing list of motes connected to router in the web page but unable to ping them... It showing "unreachable". Can any one knows please help me...

Thanks a tun in advance...

**Comment by laurentderu** [comment]
The most probable problem is that you don't have a bbbb::64 address configured on the RPi

You can either tell the RPi to create it automatically or create it manually, see https://github.com/cetic/6lbr/wiki/6LBR-Connection
