### ISSUE TITLE
Error Compiling  Example : DTLS CoAP Server

### ISSUE THREAD

**Issue by jomicobasi** [cetic/6lbr#330]
I was trying to follow [Example : DTLS CoAP Server](https://github.com/cetic/6lbr/wiki/Example-:-Dtls-Coap-Server).
I tried compiling to native using:
`make TARGET=native WITH_TINYDTLS=1 WITH_COAPSERVER=1 WITH_DTLS_COAP=1`

which **works**. Compiling to sky, **without the flags** also works:
`make TARGET=sky`

but when compiling with:
`make TARGET=sky WITH_TINYDTLS=1 WITH_COAPSERVER=1 WITH_DTLS_COAP=1`

it gives me the following error:

```
  CC        ../../apps/er-coap/er-coap-dtls.c
In file included from ../../apps/tinydtls/dtls.h:41:0,
                 from ../../apps/er-coap/er-coap-dtls.c:7:
../../apps/tinydtls/dtls_time.h:26:22: fatal error: sys/time.h: No such file or directory
compilation terminated.
../../Makefile.include:240: recipe for target 'obj_sky/er-coap-dtls.o' failed
make: *** [obj_sky/er-coap-dtls.o] Error 1
```

Need your help please!
**Thanks in advance!**

**Comment by laurentderu** [comment]
I guess sys/time.h is missing from the msp430 library, anyway the sky platform is way too small to be able to build TinyDTLS.
