### ISSUE TITLE
6lbr cannot route to linux hosts in network, but can to windows hosts

### ISSUE THREAD

**Issue by GV94** [cetic/6lbr#337]
I am trying to forward sensor messages from the 6lbr network to a webserver in my home network which writes the values to a log, if I run the webserver on my windows computer everything works. 

If I try to run the webserver on a raspberry pi, 6lbr cannot route the messages to it. 

I have tried sending data to the raspberry pi webserver both from my windows computer and from another raspberry and that works fine. It is just 6lbr that won't find linux hosts.

There is most likely no problem with 6lbr, but something with linux and router advertisements (such that 6lbr does not know about it), this was the only place I could find where I can hope to get some advice on the topic.

**Comment by laurentderu** [comment]
The most probable problem is that you don't have a route towards the WSN network created on your Raspberry (you could check this using ip -6 route on the RPi)

You can either tell the RPi to create it automatically or create it manually, see https://github.com/cetic/6lbr/wiki/6LBR-Connection
