### ISSUE TITLE
Mqtt with Watson IoT Platform

### ISSUE THREAD

**Issue by MarCast** [cetic/6lbr#338]
Hi everyone, I'm working with CC1310 and 6LBR. I would like to connect the device to the platform via the "web" page of the sensor. I can see all the settings and when I click IBM Platform, I go to the Watson IoT platform but I can not see the sensor messages. Can someone help me?

![cattura](https://user-images.githubusercontent.com/22538388/31486647-731f911a-af38-11e7-8767-ca9f35e691fc.JPG)

**Comment by MarCast** [comment]
@g-oikonomou @laurentderu

**Comment by chenek** [comment]
Do you run NAT64 on your edge router?

**Comment by MarCast** [comment]
It works! I change NAT64 for Raspberry! Thank you!
