### ISSUE TITLE
facing issue with iotivity client/server discovery using 6lbr

### ISSUE THREAD

**Issue by jchari** [cetic/6lbr#340]
Hi,

i have configured 6lbr in router mode and i prepared a iotivity - constrained server in cc2538. i am able to ping the nodes with ipv6 address. 
ping6 fd00::212:4b00:63a:4d86   become success.
so, configured a iotivity - client in 6lbr host machine. when i do, discovery with client i am able to observe the packets at tap0 interface. but those packets not transferring into network observed . 
that time, i have observed that host machine ip using as 
coap://[fe80::212:4b00:63a:4d86%25br0]:port 

can we ping nodes in link layer lave as mentioned below,
ping6 fe80::212:4b00:63a:4d86%br0

when i tried, result as followed below.
![image](https://user-images.githubusercontent.com/26871006/31573639-84b4136e-b0dd-11e7-8f4e-bc90804d264b.png)

Can any help me to make iotivity - discovery possible with 6lbr?

**Comment by laurentderu** [comment]
In router mode, the nodes are in a different subnet, and link-local addresses (fe80::/64) are not routable. If you want to reach your nodes using link-local addresses you must use Smartbridge mode (and you won't be able to reach nodes which are not neighbor of the BR)
