### ISSUE TITLE
Adaptivesec with 6lbr

### ISSUE THREAD

**Issue by ProfEng** [cetic/6lbr#342]
Hello everyone,

I need encryption for my setup but I am not sure. As I understood, noncoresec has some problems and adaptivesec is an alternative. But I am not sure about how to implement it for 6lbr and my nodes. 

If anyone has similar setup or any idea please shae with me. Any kind of help will be appreciated. 

Thanks in advance!

Aykut.

**Comment by ProfEng** [comment]
Hi again,

Isn't there anybody who gets worked adaptivesec with 6lbr?

**Comment by laurentderu** [comment]
You can check the adaptivesec demo in 6lbr/demo/adaptivesec (Or you can use noncoresec without anti replay in 6lbr/demo/llsec)
