### ISSUE TITLE
MQTT-Demo with CC2538

### ISSUE THREAD

**Issue by MarCast** [cetic/6lbr#346]
Hi everyone, I buy two cc2538 and I have a 1 SmartRF. In the first cc2538 I generate the cetic-6lbr-router and in the second chip I would like to generate the MQTT-DEMO. I have a 1 smartf, How can I use it? Can I install usb drivers on the mqtt-demo code?

**Comment by laurentderu** [comment]
Pure Contiki question, please use the Contiki ML.
