### ISSUE TITLE
UDP Server Connection From Host

### ISSUE THREAD

**Issue by ProfEng** [cetic/6lbr#348]
Hello all,

I have working setup with 6LBR(on Raspberry) a slip radio and a lot of nodes. I can see webpage, nodes on the sensor list, ping them etc. and I have UDP connection bw nodes and 6LBR. But I want to read UDP messages from python/nodejs code which runs at Raspberry Pi. But I don't know how to read it, from which address? 

If I send UDP datagrams to the Raspberry Pi, I can see them but when I send UDP datagrams to the 6LBR  I can see that server responses with payload "1" and don't know how to reach datagrams from Raspberry.

Any help will be appreciated. 

Aykut.

**Comment by laurentderu** [comment]
The UDP message exchanged between the node and 6LBR is only for demo purposes (and to test the network). If you want to have your own UDP traffic, you must implement your own UDP client and server.
