### ISSUE TITLE
cetic_6lbr_router with cc13xx+enc28j60

### ISSUE THREAD

**Issue by MarCast** [cetic/6lbr#351]
Hi, I download the last update of 6lbr. 

When I generate the cetic_6lbr_router and tested not function. In the last version, I modify in the platform/srf06-cc26xx/Makefile cc26xx-int-nvm.c to cc26xx-ext-nvm.c.  

Now I test the new 6lbr but not function. Why?

**Comment by laurentderu** [comment]
Have you been able to solve the problem ?
