### ISSUE TITLE
Lwm2m Plugin error - branch contiki-ng 

### ISSUE THREAD

**Issue by saulofr** [cetic/6lbr#382]
LDFLAGS="" make -C plugins/lwm2m-client
make[1]: Entering directory '/home/pi/6lbr/examples/6lbr/plugins/lwm2m-client'
  CC        ../../../6lbr-demo/apps/lwm2m/lwm2m.c
../../../6lbr-demo/apps/lwm2m/lwm2m.c:38:23: fatal error: rd-client.h: No such file or directory
 #include "rd-client.h"
                       ^
compilation terminated.
../../../../Makefile.include:240: recipe for target 'obj_native/lwm2m.o' failed
make[1]: *** [obj_native/lwm2m.o] Error 1
make[1]: Leaving directory '/home/pi/6lbr/examples/6lbr/plugins/lwm2m-client'
platform/native/Makefile.native:146: recipe for target 'plugins/lwm2m-client' failed
make: *** [plugins/lwm2m-client] Error 2

Any fix?

**Comment by laurentderu** [comment]
During the clean-up some indirect dependencies were removed, now the plugin references them explicitly to avoid such errors in the future.
