### ISSUE TITLE
Cannot build latest 6lbr develop branch with Contiki-NG

### ISSUE THREAD

**Issue by chenek** [cetic/6lbr#386]
I had successfull built 6lbr with contiki-ng in April this year. However, I cannot build latest 6lbr develop branch with Contiki-NG successfully now by refering to https://github.com/cetic/6lbr/wiki/Contiki-NG and doing "make WITH_CONTIKI=0 CONTIKI=~/contiki-ng all". I get the following errors. Can anyone build this successfully with latest 6lbr develop branch?

pi@raspberrypi:~ /6lbr/examples/6lbr$make WITH_CONTIKI=0 CONTIKI=~ /contiki-ng all
Makefile:183: CoAP Server is not supported with Contiki-NG
rm -f *.d *.e *.o contiki-ng-native.a *.so obj_native/*.so
rm -rf obj_native
rm -f cetic-6lbr-native.map
rm -f cetic-6lbr.native
for plugin in plugins/dummy plugins/lwm2m-client; do make CONTIKI=/home/pi/contiki-ng -C $plugin clean; done
make[1]: Entering directory '/home/pi/6lbr/examples/6lbr/plugins/dummy'
../../Makefile:183: CoAP Server is not supported with Contiki-NG
rm -f *.d *.e *.o contiki-ng-native.a *.so obj_native/*.so
rm -rf obj_native
rm -f cetic-6lbr-native.map
rm -f cetic-6lbr.native
make[1]: Leaving directory '/home/pi/6lbr/examples/6lbr/plugins/dummy'
make[1]: Entering directory '/home/pi/6lbr/examples/6lbr/plugins/lwm2m-client'
../../Makefile:183: CoAP Server is not supported with Contiki-NG
rm -f *.d *.e *.o contiki-ng-native.a *.so obj_native/*.so
rm -rf obj_native
rm -f cetic-6lbr-native.map
rm -f cetic-6lbr.native
make[1]: Leaving directory '/home/pi/6lbr/examples/6lbr/plugins/lwm2m-client'
rm -rf bin
make TARGET=native clean
make[1]: Entering directory '/home/pi/6lbr/examples/6lbr'
Makefile:183: CoAP Server is not supported with Contiki-NG
rm -f *.d *.e *.o contiki-ng-native.a *.so obj_native/*.so
rm -rf obj_native
rm -f cetic-6lbr-native.map
rm -f cetic-6lbr.native
make[1]: Leaving directory '/home/pi/6lbr/examples/6lbr'
make TARGET=native bin/cetic_6lbr_router
make[1]: Entering directory '/home/pi/6lbr/examples/6lbr'
Makefile:183: CoAP Server is not supported with Contiki-NG
make TARGET=native CETIC_6LBR_RPL_ROUTER=1 cetic-6lbr
make[2]: Entering directory '/home/pi/6lbr/examples/6lbr'
Makefile:183: CoAP Server is not supported with Contiki-NG
make[2]: *** No rule to make target 'cetic-6lbr'.  Stop.
make[2]: Leaving directory '/home/pi/6lbr/examples/6lbr'
Makefile:461: recipe for target 'bin/cetic_6lbr_router' failed
make[1]: *** [bin/cetic_6lbr_router] Error 2
make[1]: Leaving directory '/home/pi/6lbr/examples/6lbr'
Makefile:435: recipe for target 'cetic_6lbr_router-clean' failed
make: *** [cetic_6lbr_router-clean] Error 2

**Comment by laurentderu** [comment]
Just compiled it without problem using the same make command with the latest develop of 6LBR and sixlbr from Contiki-NG.

Could you check both your repositories are up to date ?

**Comment by laurentderu** [comment]
Just tested the built on a fresh RPi, the compilation works without problem. Have you done a git submodule update --init in both repositories ?
What version of Raspbian are you using ?

BTW I just noticed that GCC on the RPi throws new warnings that cause the build to abort unless you add WERROR=0 on the command line.

**Comment by chenek** [comment]
@laurentderu "git submodule update --init" did the trick to fix my trouble. Thanks for your support.
