### ISSUE TITLE
6lbr not working no error msg

### ISSUE THREAD

**Issue by e0003315** [cetic/6lbr#390]
I am running 6lbr on my rpi using the cc2650sdk sensortag as slip radio and another cc2650sdk running the web demo. I can find /dev/ttyyACM0 when i use "ls /dev/tty" only after i plug in the sensortag. 

However, I cannot run "sudo service 6lbr start" and there is no error msg.  the logs from "cat /var/log/6lbr.log" came out to be waiting for /dev/ttyACM0. The full description is as follows https://e2e.ti.com/support/wireless-connectivity/zigbee-and-thread/f/158/p/760456/2815593#pi320995=4

**Comment by chenek** [comment]
This issue has been solved by discussions in TI E2E forum so please close this issue.
