### ISSUE TITLE
DTLS decrypt problems

### ISSUE THREAD

**Issue by gcanadav** [cetic/6lbr#44]
Hello,

i am having packet lost problems while communicating 2 motes (dtls-client and dtls-server).
It only happens when the DTLS handshake try to send 3 packets ( 120 bytes each) in a aproximately 150 ms between the first and the last one.
The sender(dtls-client) sends all properly ( wireshark detects it too, properly), but the receiver(dtls-server) just receive the first one, or the second one too, but never all of them. I think that is it not problem of buffer size or queuebuf, since the defines are the following:

#define QUEUEBUF_CONF_NUM 14
#define UIP_CONF_BUFFER_SIZE 2560

Since i think that the problem is caused by the lack of the delay between sends, I would like to make a delay separation between the packets to give to the receiver some extra time to receive all properly, but the three packets are sent from a function, not directly from the main of a process, so i am only able to make some  _delay_loop_2(50000); but this doesnt work because ( i think) its stops all the retransmission by making the CPU stay busy.
I have tried by calling a second process from the function, just to make a process_wait_event_until ( etimer expired..)  but when the second process is waiting, the program returns to the first process, where the function is running, so it doesnt works too.

Any idea? Maybe any way to pause the first process from the second process while the process_wait_event is waiting.. and then resume the first process ( if its posible, i dont know..). I have read that the process_wait_event doesnt makes the CPU stay busy so i guess that the packets would be sent while the program is waiting, so i only need a way to pause the first process while the second one is waiting.

If you think that the problem is not the lack of delay between packets, tell me please.

If more information is needed, please just ask for it :)

PD: i am using Contiki-2.7, ATMEGA256RFR2, csma.c and nullrdc.

**Comment by prabhakaran1989** [comment]
Though this bug was created on june 2014, it's still open. I'm also having similar problems with tinyDTLS and wismote platform.  Did anyone solve these issues?
