### ISSUE TITLE
Er-rest-client

### ISSUE THREAD

**Issue by ghost** [cetic/6lbr#46]
Hello Guys ,
                      I have cloned the latest version 1.3.1 of 6lbr, i am trying to compile /example/6lbr-demo/ for cc2538dk evaluation module ,its compiled perfectly and able to flashed it, Now to connect it from client i need t make er-rest-client natively, but when i m trying to do that by the command "make TARGET=native er-rest-client-example , its not happening.
I have not changed anything into the code i m just compiling the code what has been provided.
Its showing the errors ,
In file included from er-example-client.c:57:0:
../../apps/er-coap-13/er-coap-13-engine.h:89:17: error: too few arguments to function ‘coap_blocking_request’
   static struct request_state_t request_state; \
                 ^
er-example-client.c:142:7: note: in expansion of macro ‘COAP_BLOCKING_REQUEST’
       COAP_BLOCKING_REQUEST(&server_ipaddr, REMOTE_PORT, request, client_chunk_handler);
       ^

Thanks ,

**Comment by latapata** [comment]
@laurentderu and @Devesh24 is the er-rest-client available now.
