### ISSUE TITLE
Deployment of 6lbr on cc2538dk Evaluation Module

### ISSUE THREAD

**Issue by ghost** [cetic/6lbr#47]
Hello Guys,
                   I am using cc2538dk EM kit for my purpose, i have gone through the whole "Hello 6lbr" thread and able to set-up everything, but when i access the 6lbr-border router web page using "[bbbb::100]" address i am not able to get any entry in the node field, i am attaching the image of that.
One more problem i am having that when i access the module on which 6lbr-demo is been flashed through UART , i am not getting any "Tentative IPv6 address " on screen as it shows on cooja , and i have tried same thing on STM32W platform there i am getting "Tentative IPv6 address". But on cc2538dk i  am getting only following 
Contiki-6lbr-1.3.1
TI SmartRF06 + cc2538EM
 Net: sicslowpan
 MAC: CSMA
 RDC: nullrdc
Rime configured with address 00:12:4b:00:89:ab:cd:ef

So it should be like that only or it should show IPv6 address too.
Please Help
Thanks 
![screenshot from 2014-06-17 17 54 42](https://cloud.githubusercontent.com/assets/5832315/3327006/54d4ea08-f7a7-11e3-8533-698dddd983b7.png)
![screenshot from 2014-06-17 17 52 49](https://cloud.githubusercontent.com/assets/5832315/3327010/5f1d0afe-f7a7-11e3-975e-6ba259bdd9d9.png)
![screenshot from 2014-06-17 17 52 34](https://cloud.githubusercontent.com/assets/5832315/3327011/6419f422-f7a7-11e3-87e8-32ecf4df9fa1.png)
![screenshot from 2014-06-17 17 52 17](https://cloud.githubusercontent.com/assets/5832315/3327013/69161cc6-f7a7-11e3-8073-4a05c982f704.png)

**Comment by Krishna421TSP** [comment]
Hi..
I am trying to deploy 6lbr on cc2538dk..
So as mentioned in Installation thread i have compiled the code and the binary cetic-6lbr.bin i have flashed it to cc2538dk.
I have connected ENC28J60 to CC2538dk Port pins as mentioned in Installation thread..
I have done the below configuration on my linux PC to setup ipv6 host as mentioned in connecting to 6LBR thread.
sudo ip -6 addr add bbbb::101/64 dev eth0
route -A inet6 add aaaa::/64 gw bbbb::100
And Trying to access web server at [bbbb::100] address on my  linux PC.

Please find below attachment for more details..

![topology](https://cloud.githubusercontent.com/assets/10338805/5591782/b4cecee8-91b1-11e4-962f-85aa58aec40a.png)

**Comment by Krishna421TSP** [comment]
Hi..Devaks09...
Module is broadcasting packets to Ethernet as well wireless network and its is getting some ICMP message as shown in log.
I think it is trying to connect to some  server address and that is not available so it is restting the chip..
If this correct can u please tell me the address to which it will connect ..?
Please find the below logs..and could you give me your views on it..

Contiki 3.x
TI SmartRF06 + cc2538EM
 Net: sicslowpan
 MAC: CSMA
 RDC: nullrdc
 Channel: 26
 PAN-ID: abcd
Rime configured with address 00:12:4b:00:04:2b:3c:c3
INFO: 6LBR: Starting 6LBR version 1.3.2 (Contiki 3.x)
INFO: NVM: Reading 6LBR NVM
INFO: NVM: NVM Magic : 2009
INFO: NVM: NVM Version : 1
TRACE: 6LE: Low2Eth translate : 00:12:4b:00:04:2b:3c:c3
TRACE: 6LE: Low2Eth adding prefix
TRACE: 6LE: Low2Eth Lowpan addr : 00:12:4b:00:04:2b:3c:c3
TRACE: 6LE: Low2Eth Ethernet addr : 06:00:04:2b:3c:c3
INFO: ECON: Eth MAC address : 06:00:04:2b:3c:c3
INFO: ETH: ENC-28J60 Process started
INFO: ETH: ENC28J60 init
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
INFO: 6LBR: Tentative local IPv6 address fe80::212:4b00:42b:3cc3
INFO: 6LBR: Tentative global IPv6 address (WSN) aaaa::212:4b00:42b:3cc3
INFO: 6LBR: Tentative global IPv6 address (ETH) bbbb::100
DEBUG: RIO: Adding route information: length=64, flags=0, route lifetime=1800, dest=aaaa::
INFO: 6LBR: RA Daemon enabled
INFO: NVM: Flashing 6LBR NVM
INFO: 6LBR: Configured as DODAG Root
INFO: 6LBR: Starting as RPL ROUTER
INFO: UDPS: UDP server started
INFO: 6LBR: CETIC 6LBR Started
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: eth_output: broadcast
TRACE: 6LE: translateIP: ICMP Message detected
PACKET: PF: eth_output: Sending packet to Ethernet
PACKET: ETH: write: 78
PACKET: ENC: tx: 78: 60:00:00:00:00:18
PACKET: ENC: sent_packets 1
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: eth_output: broadcast
PACKET: PF: eth_output: Update src address
TRACE: 6LE: translateIP: ICMP Message detected
PACKET: PF: eth_output: Sending packet to Ethernet
PACKET: ETH: write: 134
PACKET: ENC: tx: 134: 60:00:00:00:00:50
PACKET: ENC: sent_packets 2
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
DEBUG: ENC: test received_packet 0 > sent_packets 2
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: eth_output: broadcast
PACKET: PF: eth_output: Update src address
TRACE: 6LE: translateIP: ICMP Message detected
PACKET: PF: eth_output: Sending packet to Ethernet
PACKET: ETH: write: 134
PACKET: ENC: tx: 134: 60:00:00:00:00:50
PACKET: ENC: sent_packets 1
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: eth_output: broadcast
PACKET: PF: eth_output: Update src address
TRACE: 6LE: translateIP: ICMP Message detected
PACKET: PF: eth_output: Sending packet to Ethernet
PACKET: ETH: write: 134
PACKET: ENC: tx: 134: 60:00:00:00:00:50
PACKET: ENC: sent_packets 2
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:18
PACKET: ENC: received_packets 1
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:19
PACKET: ENC: received_packets 2
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
DEBUG: ENC: test received_packet 2 > sent_packets 2
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:1a
PACKET: ENC: received_packets 1
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:1b
PACKET: ENC: received_packets 2
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
DEBUG: ENC: test received_packet 2 > sent_packets 0
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:1c
PACKET: ENC: received_packets 1
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:1d
PACKET: ENC: received_packets 2
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
DEBUG: ENC: test received_packet 2 > sent_packets 0
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:1e
PACKET: ENC: received_packets 1
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
PACKET: ENC: EPKTCNT 0x01
PACKET: ENC: rx: 342: 45:00:01:48:02:1f
PACKET: ENC: received_packets 2
PACKET: ETH: read: 342
PACKET: PF: eth_input: Dropping packet type=0x0800
DEBUG: ENC: test received_packet 2 > sent_packets 0
DEBUG: ENC: test received_packet 0 > sent_packets 0
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
DEBUG: ENC: test received_packet 0 > sent_packets 0
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
PACKET: PF: bridge_output: Sending packet to Broadcast
PACKET: PF: wireless_output: sending packet
DEBUG: ENC: test received_packet 0 > sent_packets 0
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
DEBUG: ENC: test received_packet 0 > sent_packets 0
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
DEBUG: ENC: test received_packet 0 > sent_packets 0
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
DEBUG: ENC: test received_packet 0 > sent_packets 0
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6
DEBUG: ENC: test received_packet 0 > sent_packets 0
DEBUG: ENC: resetting chip
INFO: ENC: resetting chip
DEBUG: ENC: REV 6

**Comment by Krishna421TSP** [comment]
Hi..
I i have got 6lbr working..And i am able to see the web server at [bbbb::100] in windows machine..
but the same thing if try in linux machine i don't see any thing..I am running ubuntu  in  Vm ware.
Could you please tell me what could be the problem in this case..

Thanks...

**Comment by devaks09** [comment]
Hello,
          When you are running 6lbr , linux pc able to create a bridge br0 ?

**Comment by Krishna421TSP** [comment]
Hi..Devesh 
Thanks for the reply..
Could please tell me how can i do that..Do we have to issue any commands on linux PC to establish a bridge br0..

Thanks..

**Comment by devaks09** [comment]
Hello,
         check ifconfig. We dont need to issue any extra command , it is
done by 6lbr , but since you are running linux on VM  so that could a be a
problem.

**Comment by Krishna421TSP** [comment]
Hi..
if i give ifconfig the below message it shows..
user@instant-contiki:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:0c:29:a6:9c:90  
          inet addr:192.168.153.153  Bcast:192.168.153.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fea6:9c90/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:49 errors:0 dropped:0 overruns:0 frame:0
          TX packets:139 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5691 (5.6 KB)  TX bytes:23072 (23.0 KB)
          Interrupt:19 Base address:0x2000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:34 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2343 (2.3 KB)  TX bytes:2343 (2.3 KB)
May i know wt could be the problem..

Thanks..Hi..
if i give ifconfig the below message it shows..
user@instant-contiki:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 00:0c:29:a6:9c:90  
          inet addr:192.168.153.153  Bcast:192.168.153.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fea6:9c90/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:49 errors:0 dropped:0 overruns:0 frame:0
          TX packets:139 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5691 (5.6 KB)  TX bytes:23072 (23.0 KB)
          Interrupt:19 Base address:0x2000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:34 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2343 (2.3 KB)  TX bytes:2343 (2.3 KB)
May i know wt could be the problem..

**Comment by devaks09** [comment]
Hello,
        Bridge br0 is not being created.
        have you installed bridge-utils , and check with native linux not
on VM .

**Comment by Krishna421TSP** [comment]
Hi..
Does it work on Vm..?

**Comment by devaks09** [comment]
the problem could be creating br0 while running VM.

**Comment by Krishna421TSP** [comment]
Hello..
I have installed bridge utilities on VM and then i have created bridge br0.
And I am able to open web server on VM too.
Thanks for your support.

**Comment by devaks09** [comment]
Hello
Did you issue any extra command to create bridge.? I think It would have
been automatically created by 6lbr .

**Comment by Krishna421TSP** [comment]
Hi..
Yes i have issued below command to create the bridge on my VM.

brctl addbr br0
brctl addif br0 eth0
brctl addif br0 eth1
ifconfig br0 up

Thanks..

**Comment by devaks09** [comment]
Hello,
         Ok , Best of luck :)

**Comment by Krishna421TSP** [comment]
Thank you...

**Comment by latapata** [comment]
hey Guys,

I am also having the same problem. 6LBR not working. My chip is just resetting again and again. @Krishna421TSP can you please tell me how did you start working on it. Did you connect your hardware directly to computer via a crossover cable or did you do it using a router. I have burned appropriate programs but it is not working at all.

**Comment by Krishna421TSP** [comment]
Hi latapata...
may i know which hardware your using..?
If you are using CC2538dk then take a look at your NVM configuration file..

**Comment by latapata** [comment]
Hey @Krishna421TSP   I am using CC2538DK from TI. I finally managed to get things working, and the problem was with the project-conf.h file and now I am able to route properly. 

I thank you very much for the help.

**Comment by laurentderu** [comment]
What was the problem in the project-cont.h file : was it a pin mapping issue or something else ?

**Comment by latapata** [comment]
Hello Not to panic. I had changed the project-conf.h file to handle spi configuration but I was using the pins of GPIO and at the end I changed it back to GPIO. The TI documentation confused me which PIN to use for GPIO and SPI

**Comment by Krishna421TSP** [comment]
Ok Best of luck..

**Comment by Devesh24** [comment]
@latapata @Krishna421TSP
Hey guys can you please tell what all changes you made it working, like GPIO, SPI and assembly enc28j60 with cc2538.

**Comment by latapata** [comment]
@Devesh24 The probem I faced is wrong connection of enc28j60 with the CC2538dk development board. If you connect it properly this will work.

**Comment by Devesh24** [comment]
@latapata Yes it worked .. :)
