### ISSUE TITLE
slip_set_mac and slip_reboot

### ISSUE THREAD

**Issue by g-oikonomou** [cetic/6lbr#55]
I've been looking at implementing missing features (getting / setting RF channel and MAC address) in Contiki's slip-radio. It's relatively straightforward with the new RF API (assuming the radio implements it).

For 6lbr's `slip_set_mac` we can start with something as simple as this on the firmware:

```
NETSTACK_RADIO.set_object(RADIO_PARAM_64BIT_ADDR, &data[2], 8);
memcpy(&linkaddr_node_addr, &data[2], LINKADDR_SIZE);
memcpy(&uip_lladdr.addr, &linkaddr_node_addr, sizeof(uip_lladdr.addr));
```

I see that, when shutting down, 6lbr emits a `slip_set_mac(&linkaddr_null);` When starting it emits a `slip_reboot()`. This would normally be enough to restore the slip radio to the original MAC. But...

Use case:
- 6lrb native on i) BeagleBone Black / Debian or ii) Ubuntu on a normal PC
- SLIP radio on a CDC-ACM device (e.g. a CC2538 EM).

Problem: If we actually reboot upon reception of a `slip_reboot`, `/dev/ttyACMx` will disappear while 6lbr is trying to use it. This crashes my BeagleBone pretty badly (hard reset required). Ubuntu on a normal PC doesn't crash, but 6lbr enters a state whereby it blocks waiting for the device to re-appear, until it eventually gets restarted by the 6lbr watchdog. Upon restarting, 6lbr reboots the radio again, rinse-repeat like so:

```
********************************************************************************
[...]
2014-08-14 15:25:36.499057: INFO: TAP: Eth MAC address : 08:00:27:ca:34:88
2014-08-14 15:25:36.499057: INFO: BR-RDC: Reset SLIP Radio
2014-08-14 15:25:36.499074: INFO: BR-RDC: Fetching MAC address
2014-08-14 15:25:37.499156: INFO: BR-RDC: Fetching MAC address
2014-08-14 15:25:37.556806: FATAL: SLIP: read() : Success
2014-08-14 15:25:37.557064: INFO: TAP: Running 6lbr-ifdown script '/usr/lib/6lbr/6lbr-ifdown'
2014-08-14 15:25:37.590834: INFO: BR-RDC: Set MAC: 00:00:00:00:00:00:00:00
2014-08-14 15:25:37.590969: FATAL: SLIP: slip_flushbuf::write() : Input/output error
Waiting for /dev/ttyACM0
********************************************************************************
Sun Sep 14 15:25:48 BST 2014 : Starting 6LBR
/usr/lib/6lbr/bin/cetic_6lbr_router -c /etc/6lbr/nvm.dat -s /dev/ttyACM0 -t eth0 -r -B 115200 -U /usr/lib/6lbr/6lbr-ifup -D /usr/lib/6lbr/6lbr-ifdown -w /usr/lib/6lbr/www -L 3  -W /var/log/6lbr.timestamp -P 60 -C /var/log/6lbr.ip  -m /usr/lib/6lbr/plugins  
Contiki-6lbr-1.3.2 started with IPV6, RPL
[...]
2014-08-14 15:25:48.656981: INFO: TAP: Eth MAC address : 08:00:27:ca:34:88
2014-08-14 15:25:48.657044: INFO: BR-RDC: Reset SLIP Radio
2014-08-14 15:25:48.657107: INFO: BR-RDC: Fetching MAC address
2014-08-14 15:25:49.657208: INFO: BR-RDC: Fetching MAC address
2014-08-14 15:25:49.722007: FATAL: SLIP: read() : Success
2014-08-14 15:25:49.722265: INFO: TAP: Running 6lbr-ifdown script '/usr/lib/6lbr/6lbr-ifdown'
2014-08-14 15:25:49.773728: INFO: BR-RDC: Set MAC: 00:00:00:00:00:00:00:00
2014-08-14 15:25:49.774547: FATAL: SLIP: slip_flushbuf::write() : Input/output error
Waiting for /dev/ttyACM0
(repeats)
```

The error log has the respective watchdog-related entries:

```
********************************************************************************
Sun Sep 14 15:25:36 BST 2014 : Starting 6LBR
/usr/lib/6lbr/6lbr: line 206:  4277 Terminated              application_watchdog
Sun Sep 14 15:25:37 BST 2014 : /usr/lib/6lbr/bin/cetic_6lbr_router failed, exit code: 1
(repeats)
```

We can't really ignore the reset command, because we end up with a MAC of all zeros, so it's really either both or neither.

My current workaround:
- Save h/w MAC in a variable at slip-radio startup
- Implement `slip_set_mac`
- For `slip_reboot`, we don't _really_ reboot, we just re-set RF registers and data structures to the h/w MAC.

But this isn't really ideal:
- Do we need to set the MAC to all zeros at the radio? Not 100% familiar with 6lbr's various modes of operation yet, but could we bypass that step on shutdown?
- Are there any other reasons to reboot the radio? Could we simply save the MAC somewhere on exit and restore it on startup? Am I introducing a subtle problem by _not_ rebooting when 6lbr thinks I have?

Thanks

(and yes @sdawans , there will be docs! :smile: )

**Comment by aniketdali** [comment]
Hello, I am new to this forum,

Could you please explain the workaround to restrain 6LBR from "FATAL: SLIP: slip_flushbuf::write()". 

Where shall I make changes for the following

"
    Save h/w MAC in a variable at slip-radio startup
    Implement slip_set_mac
    For slip_reboot, we don't really reboot, we just re-set RF registers and data structures to the h/w MAC.
"

- Thank You
