### ISSUE TITLE
Observe feature is not working

### ISSUE THREAD

**Issue by Devesh24** [cetic/6lbr#64]
Hello Guys,
                    I am trying to run er-example-server as 6lbr-demo to get the test/push resource working.
I got the topology up as the "hello-6lbr" thread says, but the problem i am facing with the observe feature Whenever i send the simple GET request to /test/push resource through copper plugin i got the ACK, but when i try to observe the /test/push then only for first time i got ACK but further no NON CONFIRMABLE notification i am getiing, for the first time when i got ACK its showing Observe 0 that is supposed to incresed after but its not.
I tried to debug the problem so i got the flow of functions fine as below
observing->transaction->udp
but i am not getting any subsequent notification ACK packet on wireshark. On the contiki everythin is working fine.
I am pasting my debug logs below
/*------------------------------------------------------------------------------------------------------*/
Observing: Notification from test/push
           Observer [bbbb:0000:0000:0000:75ca:491a:5cf0:fb7b]:25320
Sending transaction 23404
UIP_UDP
UIP_CONF_IPV6
-sent UDP datagram (16)-
Freeing transaction 23404: #0x20000d7c
UIP_UDP
UIP_CONF_IPV6 
Observing: Notification from test/push
           Observer [bbbb:0000:0000:0000:75ca:491a:5cf0:fb7b]:25320
Sending transaction 23405
UIP_UDP
UIP_CONF_IPV6
-sent UDP datagram (16)-
Freeing transaction 23405: #0x20000d7c
UIP_UDP
UIP_CONF_IPV6
/*------------------------------------------------------------------------------------------------------------*/
Thanks

**Comment by Devesh24** [comment]
@laurentderu 
Hello ,
            Sorry for the delay to respond. I have checked all the logs but i dont see any packets coming upto 6lbr, i have checked with wireshark too but no packets coming from observe resource.
Thanks

**Comment by Devesh24** [comment]
Hello Guys ,
                    If i am using contiki er-example-server with 6lbr native border router, observe works fine .
  So i think issue is with 6lbr observing. Any lead ?
Thanks

**Comment by latapata** [comment]
Hello @Devesh24 I am also trying to get the same thing done. I have 6LBR native border router and have programmed er-rest-server on cc2538dk. I have a question are you getting the route information on the 6LBR homepage. 
I am not even getting routed to the coap server.

**Comment by Devesh24** [comment]
@latapata Hey, can you paste the method or function that having the code to turn LED ON .

**Comment by latapata** [comment]
@Devesh24 I am using the COAP of 6lbr-demo I do not have any specific methods as such. In the COAP 6lbr-Demo the leds-resource has the method defined but I am not really getting how to use this. Meanwhile the button sensor as well. 

Thanks for your help.

**Comment by Devesh24** [comment]
@latapata Are you using cc2538dk EM and what coap-client you are using copper plugin ?

**Comment by Devesh24** [comment]
Hey dude you can create a different issue ? current issue is not related to your help . 
Thanks .

**Comment by latapata** [comment]
@Devesh24 Thanks for the information. I will open a seperate thread.
