### ISSUE TITLE
Mesh network not working properly 

### ISSUE THREAD

**Issue by Devesh24** [cetic/6lbr#67]
Hello Guys,
                   I am working on a project where i am using 6lbr for routing. I am using cc2538 EM , here i am facing strange problem with mesh network, problem is that as long as a mote directly connected to slip-radio the mote getting ping, but when it got connected to slip-radio  via another mote the mote stopped pinging.
I have made following changes,
In /platform/cc2538/
UIP_CONF_IPV6 =1
UIP_CONF_IPV6_RPL =1 ,
PANID = 0XABCD
CHANNEL = 26
Any lead ?

Thanks

**Comment by Devesh24** [comment]
Any lead ?

**Comment by Devesh24** [comment]
Hello Guys 
Any tips or lead ?
@g-oikonomou 
@malvira

**Comment by malvira** [comment]
Sorry no clue. Haven't really kept up with the latest or greatest in these matters.
