### ISSUE TITLE
coap client in 6lbr

### ISSUE THREAD

**Issue by latapata** [cetic/6lbr#74]
Hello All,

I am in a need of er-coap-client on cc2538dk. I have a nodejs coap server running on my PC and I need my cc2538dk client to interact with this over 6lbr network. The cc2538dk just sends a button press information through POST mehtod of COAP. Any help is greatly appreciated.

I also looked at issue #46 but I did not understand what was mentioned.

**Comment by laurentderu** [comment]
There is a functional coap client in the develop branch of 6LBR, it supports POST, PUT as well ass asynchronous push and dynamic binding.

**Comment by latapata** [comment]
Hello @laurentderu 

Thanks a million for the reply. Where can I find and How can I use it ?

**Comment by laurentderu** [comment]
For the time being, it's available in 6lbr-demo/apps/coap. You can have a look at coap-push.c and binding-table.c The next version should be more clear and easier to use.

**Comment by latapata** [comment]
I do not see any coap-push.c in 6lbr/examples/6lbr-demo/apps/coap as well as the coap-push.c

**Comment by sdawans** [comment]
it's on the ``develop`` branch

https://github.com/cetic/6lbr/tree/develop/examples/6lbr-demo/apps/coap

**Comment by latapata** [comment]
@sdawans Thanks a lot !!

**Comment by shantanoo-desai** [comment]
Hello I have some similar work. A bunch of CoAP servers keep sending some information like eui,temp and Up time counts to a linux pc which is connected to 6lbr router (in router mode). I need to show the information as of now just on the terminal window or a text file. What could be an optimum solution for make the PC like a SINK which can just keep collecting values?

Thanks.
Shan

the work looks something like this..

![ex1](https://cloud.githubusercontent.com/assets/12070966/8305932/d8dfe2d8-19b3-11e5-8ef6-c3590f3ad21d.png)
