### ISSUE TITLE
XM1000 - ERROR: SLIP: Unknown command

### ISSUE THREAD

**Issue by araciti** [cetic/6lbr#78]
I have two XM1000 motes and I wish to run Hello 6LBR example on RaspberryPi
http://www.advanticsys.com/wiki/index.php?title=XM1000

I already tested my motes using native-border-router from contiki 2.7 and they worked correctly.

Now I'm trying to use cetic-6lbr-1.3.2 on raspeberry
https://github.com/cetic/6lbr/wiki/RaspberryPi-Software-Configuration

I've made many attemps, but unfortunatly I always get this error
ERROR: SLIP: Unknown command

It seems that 6lbr router is not compatible with Contiki 2.7 slip radio application

I tried to compile xm1000 drivers into cetic/6lbr Contiki fork, but there are too many differences comparison Contiki 2.7

What can I do?

**Comment by laurentderu** [comment]
Hi,

6LBR is compatible with 2.7 slip radio. The catch is that 6LBR uses an extra command to reset the slip-radio at startup in order to be sure of the slip-radio state. That command is not available in 2.7, but the slip)radio will anyway be functional.
