### ISSUE TITLE
Change in address for getting debian releases

### ISSUE THREAD

**Issue by shantanoo-desai** [cetic/6lbr#87]
Hello,

I was trying to get the recent debian package on Raspberry Pi according to the documentation and for the given link address in the <pre>wget https://raw.github.com/wiki/cetic/6lbr/releases/cetic-6lbr_1.3.2-0_armhf.deb</pre> is not valid since the output on my Pi is the following:

<pre>pi@raspberrypi ~ $ wget https://raw.github.com/wiki/cetic/6lbr/releases/cetic-6lbr_1.3.3_armhf.deb
--2015-06-18 12:50:20--  https://raw.github.com/wiki/cetic/6lbr/releases/cetic-6lbr_1.3.3_armhf.deb
Resolving raw.github.com (raw.github.com)... 185.31.17.133
Connecting to raw.github.com (raw.github.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/wiki/cetic/6lbr/releases/cetic-6lbr_1.3.3_armhf.deb [following]
--2015-06-18 12:50:25--  https://raw.githubusercontent.com/wiki/cetic/6lbr/releases/cetic-6lbr_1.3.3_armhf.deb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-06-18 12:50:29 ERROR 404: Not Found.</pre>

The solution for this is a change in the address 
<pre> wget https://raw.github.com/wiki/cetic/6lbr/releases/rpi/cetic-6lbr_1.3.3_armhf.deb</pre>

<b>releases/rpi/</b> is the right path for getting the debian package..

Please do change the needful in the wiki so other people do not have a problem. 

regards,
Shan

**Comment by laurentderu** [comment]
Thanks for the catch, it's fixed now
